import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir,writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import express from 'express';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {createCanvas} from '@napi-rs/canvas';
import ffmpeg from 'ffmpeg-static';
import {Store} from '../server/store.mjs';
import {Harness} from '../server/harness.mjs';
import {Desktop} from '../server/desktop.mjs';
import {mountExtensions} from '../server/extension-routes.mjs';
import {retrieve} from '../server/knowledge.mjs';
import {execute} from '../server/process.mjs';
import {invoke,verifyImageReads} from '../server/runtimes.mjs';
import {publicAddress,fetchPublic,parsePage,addResource,archivePage,syncAssets,prepareResource,validateAssessment,resourceContext} from '../server/resources.mjs';

const input={prompt:'Explica cómo DHCP asigna una dirección IP al cliente.',duration:15,runtime:'demo',architecture:'tools',context:'minimal',style:'technology',concurrency:3,desktop:false,sources:[],options:{webResearch:true}};
const board={title:'DHCP',scenes:[{id:'s1',title:'Cliente y servidor',duration:15,narration:'DHCP asigna una dirección IP.',type:'diagram',eyebrow:'REDES',points:['Cliente','Servidor'],sourceIds:[]}]};
async function setup(t,dependencies={}){const folder=await mkdtemp(path.join(os.tmpdir(),'lumen-resources-')),store=new Store(folder),desktop=new Desktop(store),harness=new Harness(store,desktop,dependencies);t.after(async()=>{store.close();assert.ok(path.resolve(folder).startsWith(path.join(os.tmpdir(),'lumen-resources-')));await rm(folder,{recursive:true,force:true});});return {store,desktop,harness,project:await harness.create(structuredClone(input)),folder};}
function assessment(resources){return {summary:'Recursos examinados.',resources:resources.map(resource=>({resourceId:resource.id,inspected:!!resource.previewPaths?.length,score:resource.previewPaths?.length?85:null,recommendation:resource.previewPaths?.length?'use':'reserve',relevance:'Representa el cliente y el servidor.',quality:'Legible.',compositionFit:'Permite explicar el flujo.',suggestedUse:'Introducción al proceso.',limitations:resource.kind==='video'?['Solo se han examinado fotogramas.']:[]}))};}
async function localImage(store,harness,id,name='Diagrama DHCP'){const folder=harness.folder(id);await mkdir(path.join(folder,'media'),{recursive:true});const canvas=createCanvas(800,450),ctx=canvas.getContext('2d');ctx.fillStyle='#eef1ff';ctx.fillRect(0,0,800,450);ctx.fillStyle='#58499e';ctx.font='bold 32px sans-serif';ctx.fillText('CLIENTE  →  SERVIDOR DHCP',50,210);const file='media/'+name.replace(/\W/g,'-')+'.png';await writeFile(path.join(folder,file),canvas.toBuffer('image/png'));const project=store.get(id);project.assets.push({id:name,name,kind:'image',path:file,size:1000,origin:'upload'});store.save(project);syncAssets(store,id);return store.get(id).resources.find(resource=>resource.assetId===name);}

test('las páginas consultadas guardan texto, medios, procedencia y conocimiento sin borrar el plan',async t=>{
  const {store,harness,project}=await setup(t);const current=store.get(project.id);current.tasks=[{id:'accepted',kind:'research',status:'completed',dependencies:[],output:{summary:'Conservado'}}];store.save(current);
  const html='<title>Guía DHCP</title><main>El arrendamiento DHCP configura la dirección del equipo.</main><img src="/diagram.png" alt="Flujo DHCP"><video src="https://cdn.example.com/clip.mp4"></video><img width="1" src="/tracker.png"><script>"<img src=\"/fake.png\">"</script>';
  const fetcher=async url=>({body:Buffer.from(html),mime:'text/html',url});
  const page=await archivePage(store,project.id,'https://example.com/dhcp',{taskId:'research-1',fetcher});
  assert.equal(page.status,'consulted');assert.equal(page.name,'Guía DHCP');assert.equal(store.get(project.id).resources.length,3);assert.equal(store.get(project.id).tasks[0].output.summary,'Conservado');assert.match(retrieve(store,project.id,'arrendamiento')[0].text,/DHCP/);assert.equal(retrieve(store,project.id,'arrendamiento')[0].sourceId,page.id);
  const image=store.get(project.id).resources.find(resource=>resource.kind==='image');assert.equal(image.url,'https://example.com/diagram.png');assert.equal(image.sourceUrl,page.url);assert.equal(image.license,undefined);
  await archivePage(store,project.id,page.url,{fetcher:async()=>{throw new Error('No debe repetirse');}});assert.equal(store.get(project.id).resources.length,3);
  await harness.export(project.id);assert.equal(JSON.parse(await readFile(path.join(harness.folder(project.id),'resources.json'),'utf8')).length,3);
});
test('consultas concurrentes conservan ambas páginas; los fallos quedan como referencias',async t=>{
  const {store,project}=await setup(t),fetcher=async url=>{await new Promise(resolve=>setTimeout(resolve,url.endsWith('one')?25:5));return {url,mime:'text/html',body:Buffer.from('<title>'+url+'</title><img src="/image.png">')};};
  await Promise.all(['one','two'].map(part=>archivePage(store,project.id,'https://example.com/'+part,{fetcher})));
  assert.equal(store.get(project.id).resources.filter(resource=>resource.kind==='page').length,2);assert.equal(store.get(project.id).resources.filter(resource=>resource.kind==='image').length,1);
  await archivePage(store,project.id,'https://example.com/missing',{fetcher:async()=>{throw new Error('HTTP 404');}});const failed=store.get(project.id).resources.find(resource=>resource.url.endsWith('missing'));assert.equal(failed.status,'reference');assert.equal(failed.error,'HTTP 404');assert.equal(failed.content,undefined);
});
test('prepara píxeles reales y tres fotogramas de vídeo con sus tiempos',async t=>{
  const {store,harness,project}=await setup(t),image=await localImage(store,harness,project.id),signal=new AbortController().signal;
  const prepared=await prepareResource(store,project.id,image.id,harness.folder(project.id),signal);assert.equal(prepared.status,'ready');assert.equal(prepared.metadata.width,800);assert.equal(prepared.previewPaths.length,1);assert.ok((await readFile(path.join(harness.folder(project.id),prepared.previewPaths[0].path))).length>1000);
  const filename='media/demo.mp4';const result=await execute(ffmpeg,['-y','-loglevel','error','-f','lavfi','-i','testsrc2=size=640x360:rate=12','-t','2','-c:v','libx264','-threads','1',path.join(harness.folder(project.id),filename)],{signal});assert.equal(result.code,0);const current=store.get(project.id);current.assets.push({id:'clip',name:'Demostración',path:filename,kind:'video'});store.save(current);syncAssets(store,project.id);
  const video=store.get(project.id).resources.find(resource=>resource.assetId==='clip'),frames=await prepareResource(store,project.id,video.id,harness.folder(project.id),signal);assert.equal(frames.previewPaths.length,3);assert.deepEqual(frames.previewPaths.map(frame=>frame.time),[.2,1,1.8]);assert.equal(frames.metadata.height,360);
});
test('la valoración impide inventar inspecciones, puntuaciones e identificadores',()=>{
  const resource={id:'candidate',kind:'image',previewPaths:[]},result=assessment([resource]);assert.ok(validateAssessment(result,[resource]));assert.throws(()=>validateAssessment({...result,resources:[{...result.resources[0],inspected:true,score:80,recommendation:'use'}]},[resource]),/sin previsualización/);assert.throws(()=>validateAssessment({...result,resources:[{...result.resources[0],score:80}]},[resource]),/no admite nota/);assert.throws(()=>validateAssessment({...result,resources:[{...result.resources[0],resourceId:'invented'}]},[resource]),/inexistente/);
});
test('el DAG espera toda la investigación y entrega valoraciones al diseñador; no repite recursos al reanudar',async t=>{
  const calls=[],{store,harness,project}=await setup(t,{runtimeInvoke:async args=>{calls.push(args.kind);if(args.kind==='plan')return {output:{reasoning:'Investigar en paralelo.',tasks:[{id:'r1',kind:'research',role:'investigador',label:'Investigar 1',instruction:'Revisar',dependencies:[]},{id:'r2',kind:'research',role:'investigador',label:'Investigar 2',instruction:'Revisar',dependencies:[]},{id:'board',kind:'storyboard',role:'storyboard',label:'Diseñar',instruction:'Diseñar',dependencies:['r1']}]},metrics:{}};if(args.kind==='research'){await new Promise(resolve=>setTimeout(resolve,args.task.id==='r2'?30:5));return {output:{summary:'DHCP',sources:[],resources:[]},metrics:{}};}if(args.kind==='resource-review'){assert.equal(args.context.frames.length,1);assert.ok(args.context.frames[0].path.startsWith(harness.folder(project.id)));return {output:assessment(args.context.reviewResources),metrics:{model:'test-vision'}};}assert.equal(calls.filter(kind=>kind==='research').length,2);assert.equal(args.context.resources[0].assessment.score,85);return {output:board,metrics:{}};},sceneProducer:async()=>({duration:15}),renderer:async()=>({path:'video.mp4'}),mediaReviewer:async()=>({approved:true})});
  await localImage(store,harness,project.id);await harness.execute(project.id,new AbortController().signal);assert.equal(store.get(project.id).status,'completed');assert.ok(calls.indexOf('resource-review')<calls.indexOf('storyboard'));assert.equal(store.get(project.id).resources[0].assessment.model,'test-vision');const before=calls.length;await harness.execute(project.id,new AbortController().signal);assert.equal(calls.length,before);assert.ok(store.get(project.id).tasks.find(task=>task.kind==='storyboard').dependencies.includes('r2'));
});
test('modo supervisado pausa tras investigación y valoración y conserva artefactos al cambiar a automático',async t=>{
  const calls=[],{store,harness,project}=await setup(t,{runtimeInvoke:async args=>{calls.push(args.kind);if(args.kind==='plan')return {output:{reasoning:'Por etapas',tasks:[{id:'research',kind:'research',role:'investigador',label:'Investigar',instruction:'Revisar',dependencies:[]},{id:'board',kind:'storyboard',role:'storyboard',label:'Storyboard',instruction:'Diseñar',dependencies:['research']}]},metrics:{}};if(args.kind==='research')return {output:{summary:'DHCP',sources:[]},metrics:{}};if(args.kind==='resource-review')return {output:assessment(args.context.reviewResources),metrics:{}};return {output:board,metrics:{}};},sceneProducer:async()=>({duration:15}),renderer:async()=>({path:'video.mp4'}),mediaReviewer:async()=>({approved:true})});
  await localImage(store,harness,project.id);await harness.configure(project.id,{options:{approvalGates:true}});await harness.execute(project.id,new AbortController().signal);assert.equal(store.get(project.id).status,'needs-approval');assert.ok(!calls.includes('resource-review'));await harness.approveArtifact(project.id,'research');await harness.execute(project.id,new AbortController().signal);assert.equal(store.get(project.id).status,'needs-approval');assert.ok(!calls.includes('storyboard'));
  await harness.configure(project.id,{options:{approvalGates:false}});await harness.execute(project.id,new AbortController().signal);assert.equal(store.get(project.id).status,'completed');assert.equal(calls.filter(kind=>kind==='research').length,1);assert.equal(calls.filter(kind=>kind==='resource-review').length,1);const rendered=store.get(project.id).render;await harness.configure(project.id,{options:{approvalGates:true}});assert.deepEqual(store.get(project.id).render,rendered);
});
test('las herramientas MCP muestran imágenes reales y respetan permisos y aislamiento entre proyectos',async t=>{
  const {store,harness,desktop,project}=await setup(t),image=await localImage(store,harness,project.id),app=express();app.use(express.json());mountExtensions(app,{store,harness,desktop});app.use((error,req,res,next)=>res.status(400).json({error:error.message}));const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const base=`http://127.0.0.1:${server.address().port}`,token='resource-token';desktop.tokens.set(token,{projectId:project.id,kind:'research'});
  const client=new Client({name:'resources-test',version:'1.0.0'});t.after(async()=>{await client.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));});await client.connect(new StdioClientTransport({command:process.execPath,args:[path.resolve('server/mcp.mjs')],env:{...process.env,LUMEN_PROJECT_ID:project.id,LUMEN_SERVER_URL:base,LUMEN_MCP_TOKEN:token,LUMEN_DESKTOP_TOOLS:'0'},stderr:'pipe'}));
  const result=await client.callTool({name:'resource_preview',arguments:{resourceId:image.id}});assert.equal(result.isError,undefined);assert.equal(result.content[1].type,'image');assert.equal(result.content[1].mimeType,'image/jpeg');assert.ok(result.content[1].data.length>1000);
  const other=await harness.create({...input,prompt:'Explica otro proyecto de redes completamente separado.'});const unauthorized=await fetch(base+'/api/internal/project',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({projectId:other.id,action:'resource-preview',params:{resourceId:image.id}})});assert.equal(unauthorized.status,403);
  await harness.configure(project.id,{options:{webResearch:false}});const denied=await client.callTool({name:'resource_search',arguments:{query:'DHCP',kind:'image',provider:'commons'}});assert.equal(denied.isError,true);
});
test('bloquea destinos privados, esquemas peligrosos y previsualizaciones fuera del proyecto',async t=>{
  for(const address of ['127.0.0.1','10.0.0.5','172.16.1.1','172.31.255.1','192.168.1.4','169.254.1.1','::1','fe80::1','fd00::1','::ffff:127.0.0.1'])assert.equal(publicAddress(address),false,address);
  assert.equal(publicAddress('8.8.8.8'),true);assert.equal(publicAddress('2606:4700:4700::1111'),true);await assert.rejects(()=>fetchPublic('http://127.0.0.1'),/público/);await assert.rejects(()=>fetchPublic('https://example.com',{domains:['rfc-editor.org']}),/permitido/);assert.equal(parsePage('<img src="javascript:alert(1)"><img><video src="file:///secret">','https://example.com').media.length,0);
  const {store,harness,project}=await setup(t);const current=store.get(project.id);current.assets.push({id:'bad',name:'Fuera',kind:'image',path:'../secret.png'});store.save(current);syncAssets(store,project.id);const resource=store.get(project.id).resources[0],prepared=await prepareResource(store,project.id,resource.id,harness.folder(project.id),new AbortController().signal);assert.equal(prepared.status,'unavailable');assert.match(prepared.error,/fuera del proyecto/);
});
test('el modo demo conserva una valoración honesta sin simular visión',async t=>{
  const {harness,project,folder}=await setup(t);const resource={id:'test',kind:'image',previewPaths:[]};const result=await invoke({kind:'resource-review',project,task:{role:'revisor'},context:{reviewResources:[resource],frames:[]},attemptDir:path.join(folder,'demo-review'),signal:new AbortController().signal});assert.equal(result.output.resources[0].inspected,false);assert.equal(result.output.resources[0].score,null);assert.match(result.output.summary,/no se ha realizado/);
});
test('Claude solo puede declarar inspección si Read entregó realmente todas las imágenes',()=>{
  const output={resources:[{resourceId:'one',inspected:true}]},context={frames:[{resourceId:'one',path:path.resolve('frame.jpg')}]},call={type:'tool_use',id:'read1',name:'Read',input:{file_path:context.frames[0].path}},image={type:'tool_result',tool_use_id:'read1',content:[{type:'image'}]};
  assert.throws(()=>verifyImageReads(output,context,[{message:{content:[call]}}]),/No consta/);assert.throws(()=>verifyImageReads(output,context,[{message:{content:[call,{...image,is_error:true}]}}]),/No consta/);verifyImageReads(output,context,[{message:{content:[call,image]}}]);
  assert.throws(()=>verifyImageReads(output,{frames:[...context.frames,{resourceId:'one',path:path.resolve('frame2.jpg')}]},[{message:{content:[call,image]}}]),/muestras/);verifyImageReads({resources:[{resourceId:'one',inspected:false}]},context,[]);
});
