import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {readFile,mkdir,writeFile,stat} from 'node:fs/promises';
import ffmpeg from 'ffmpeg-static';
import {execute} from './process.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export async function whisperPaths(){const tools=process.env.LUMEN_TOOLS_DIR||path.join(root,'.tools');let executable=process.env.LUMEN_WHISPER_BIN;try{executable||=(await readFile(path.join(tools,'whisper/cli-path.txt'),'utf8')).trim();}catch{}if(executable&&!path.isAbsolute(executable))executable=path.join(tools,executable);const model=process.env.LUMEN_WHISPER_MODEL||path.join(tools,'whisper/ggml-tiny.bin');try{await stat(executable);await stat(model);return {ready:true,executable,model};}catch{return {ready:false};}}
export function wordErrorRate(expected,actual){const words=value=>(value.normalize('NFD').replace(/\p{M}/gu,'').toLowerCase().match(/[\p{L}\p{N}]+/gu)||[]);const a=words(expected),b=words(actual);let row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const next=[i];for(let j=1;j<=b.length;j++)next[j]=Math.min(row[j]+1,next[j-1]+1,row[j-1]+(a[i-1]===b[j-1]?0:1));row=next;}return {rate:row[b.length]/Math.max(1,a.length),edits:row[b.length],expectedWords:a.length,recognizedWords:b.length};}
export async function transcribeAudio(file,output,signal){
  const config=await whisperPaths();if(!config.ready)throw new Error('Instala Whisper local desde Conexiones para revisar el audio real.');
  const result=await execute(config.executable,['-m',config.model,'-f',file,'-l','es','-ojf','-of',output,'-t','4'],{signal,timeout:1800000});await writeFile(output+'.log',result.stdout+'\n'+result.stderr);if(result.code!==0)throw new Error('Whisper no pudo transcribir el audio: '+result.stderr.slice(-800));
  const json=JSON.parse(await readFile(output+'.json','utf8'));const segments=(json.transcription||[]).map(segment=>({text:segment.text.trim(),start:(segment.offsets?.from||0)/1000,end:(segment.offsets?.to||0)/1000}));return {text:segments.map(segment=>segment.text).join(' '),segments,engine:'whisper.cpp',model:path.basename(config.model)};
}
export async function reviewAudio(project,folder,signal){
  const directory=path.join(folder,'review/audio');await mkdir(directory,{recursive:true});const results=[],issues=[];let offset=0;
  for(const scene of project.storyboard.scenes){signal.throwIfAborted();const media=project.render.media[scene.id],duration=media.duration,file=path.join(directory,scene.id+'.wav');const decoded=await execute(ffmpeg,['-y','-v','error','-ss',String(offset),'-i',path.join(folder,project.render.path),'-t',String(Math.min(duration,media.speechDuration+1)),'-ar','16000','-ac','1','-c:a','pcm_s16le',file],{signal,timeout:120000});if(decoded.code!==0)throw new Error('No se pudo extraer el audio del MP4.');const actual=await transcribeAudio(file,path.join(directory,scene.id),signal),comparison=wordErrorRate(scene.narration,actual.text),syncDelta=actual.segments.length&&media.words?.length?Math.abs(actual.segments[0].start-media.words[0].start):null;
    if(!actual.text.trim())issues.push({severity:'error',sceneId:scene.id,message:'No se reconoce narración en el audio renderizado.'});else if(comparison.rate>.35)issues.push({severity:'warning',sceneId:scene.id,message:`La transcripción difiere del guion (${Math.round(comparison.rate*100)}% de error de palabras). Comprueba pronunciación y posibles errores de reconocimiento.`});if(syncDelta>1)issues.push({severity:'warning',sceneId:scene.id,message:'El comienzo reconocido y el subtítulo difieren más de un segundo.'});results.push({sceneId:scene.id,expected:scene.narration,...actual,comparison,syncDelta,offset});offset+=duration;
  }
  const review={approved:!issues.some(issue=>issue.severity==='error'),summary:'Audio extraído del MP4 y transcrito localmente; contrastado con guion y tiempos de subtítulos.',issues,scenes:results,limitations:['El reconocimiento puede confundir siglas y nombres propios.','La diferencia de transcripción señala posibles problemas; no certifica la pronunciación.']};await writeFile(path.join(directory,'review.json'),JSON.stringify(review,null,2));return review;
}
