// Rutas de proyectos (colecciones de vídeos) y de la herencia de ajustes de cada vídeo.
import path from 'node:path';
import {rm} from 'node:fs/promises';
import {createCollection,updateCollection,staleVideos,effectiveSettings,availableModels,agentPreset,INHERITED_KEYS,stable} from './collections.mjs';
import {validateCreate} from './schemas.mjs';
import {mkdir,rename} from 'node:fs/promises';
import {createWriteStream} from 'node:fs';
import {pipeline} from 'node:stream/promises';
import {randomUUID} from 'node:crypto';
import {mediaItems,findMedia,queueIndex,mediaInfo,searchMedia,cleanCut,removeBackground,detectBeats,indexDirectory} from './media-index.mjs';
import {collectionFolder,collectionStore,syncCollection} from './library-sync.mjs';
import {readFile,readdir,stat as statFile} from 'node:fs/promises';
import {kitDir,kitsOf,kitOf,KIT_ENGINES,migrateKits,componentUsage} from './collection-agents.mjs';
import {LIBRARY_KINDS,kindFor,processItem,libraryItems,libraryItem,searchLibrary} from './project-library.mjs';
import {sourceFiles,listHistory,restoreHistory,sourceHash,snapshotScene,lintScene,writeSourceFile,snapshotSources} from './scene-code.mjs';
const UPLOAD_KINDS={image:['.png','.jpg','.jpeg','.webp','.gif'],video:['.mp4','.webm','.mov','.mkv','.m4v'],audio:['.wav','.mp3','.ogg','.m4a','.aac','.flac']};

const validateSettings=values=>validateCreate({...Object.fromEntries(INHERITED_KEYS.map(key=>[key,values[key]])),prompt:'Validación de ajustes del proyecto',duration:60,sources:[]});
const running=video=>['planning','running','rendering'].includes(video.status);

export function mountCollections(app,{store,harness,agents}){
  const route=fn=>async(req,res,next)=>{try{await fn(req,res);}catch(error){next(error);}};
  const find=req=>{const collection=store.getCollection(req.params.cid);if(!collection)throw Object.assign(new Error('Proyecto inexistente.'),{status:404});return collection;};
  const summary=collection=>{const videos=store.list().filter(video=>video.collectionId===collection.id);return {...collection,videoCount:videos.length,running:videos.filter(running).length,completed:videos.filter(video=>['completed','approved'].includes(video.status)).length,lastVideoAt:videos[0]?.updatedAt||null};};
  async function removeVideo(id){if(harness.active.has(id))throw new Error('Detén el vídeo antes de borrarlo.');store.deleteProject(id);const folder=path.resolve(harness.folder(id));if(folder.startsWith(path.resolve(store.root,'projects')+path.sep))await rm(folder,{recursive:true,force:true});}

  // ---------- Biblioteca de material del proyecto ----------
  const cstore=collectionStore(store),cfolder=cid=>collectionFolder(store,cid),sync=cid=>syncCollection(store,cid,id=>harness.folder(id),harness.active);
  const index=(cid,mediaId)=>queueIndex(cstore,cid,cfolder(cid),mediaId,()=>sync(cid));
  const process=(cid,id)=>{const kind=store.getCollection(cid)?.assets?.find(asset=>asset.id===id)?.kind;if(['image','video','music','voice'].includes(kind))return index(cid,id);return processItem(cstore,cid,cfolder(cid),id,{db:store}).then(()=>sync(cid));};
  app.get('/api/collections/:cid/library',route(async(req,res)=>res.json(libraryItems(find(req)))));
  app.get('/api/collections/:cid/library/:itemId',route(async(req,res)=>{const collection=find(req),item=await libraryItem(collection,cfolder(collection.id),req.params.itemId);if(item.contactSheet)item.contactSheet=path.relative(cfolder(collection.id),item.contactSheet).replaceAll('\\','/');res.json(item);}));
  app.get('/api/collections/:cid/library-search',route(async(req,res)=>{const collection=find(req);res.json(await searchLibrary(store,collection,[collection.id],cfolder(collection.id),String(req.query.q||'')));}));
  app.post('/api/collections/:cid/library/research',route(async(req,res)=>{find(req);res.json(agents.research({kind:'collection',id:req.params.cid},{brief:String(req.body?.brief||'').slice(0,4000)}));}));
  app.get('/api/collections/:cid/media',route(async(req,res)=>{const collection=find(req);res.json(mediaItems(collection).map(item=>({...item,index:collection.mediaIndex?.[item.id]||{status:'pending'}})));}));
  app.post('/api/collections/:cid/assets/upload',route(async(req,res)=>{
    find(req);const name=String(req.query.name||'archivo').slice(0,200),extension=path.extname(name).toLowerCase(),kind=kindFor(extension,req.query.role);
    if(!kind)throw new Error('Formato no compatible. Usa imágenes, vídeo, audio, documentos (pdf, txt, md, html) o datos (csv, tsv, json).');
    const limit=4*1024**3;if(Number(req.headers['content-length']||0)>limit)throw new Error('El archivo supera 4 GB.');
    const file='media/upload-'+randomUUID()+extension,target=path.join(cfolder(req.params.cid),file),temp=target+'.part';await mkdir(path.dirname(target),{recursive:true});
    let size=0;req.on('data',chunk=>{size+=chunk.length;if(size>limit)req.destroy(new Error('El archivo supera 4 GB.'));});
    try{await pipeline(req,createWriteStream(temp));if(size<16)throw new Error('Archivo vacío.');await rename(temp,target);}catch(error){await rm(temp,{force:true});throw error;}
    const collection=store.getCollection(req.params.cid),asset={id:randomUUID(),name,path:file,kind,size,createdAt:new Date().toISOString(),origin:'upload'};
    collection.assets=[...(collection.assets||[]),asset];store.saveCollection(collection);process(collection.id,asset.id);await sync(collection.id);res.status(201).json(asset);
  }));
  app.get('/api/collections/:cid/media/:mediaId',route(async(req,res)=>{const collection=find(req),info=await mediaInfo(collection,cfolder(collection.id),req.params.mediaId);if(info.contactSheet)info.contactSheet=path.relative(cfolder(collection.id),info.contactSheet).replaceAll('\\','/');res.json(info);}));
  app.post('/api/collections/:cid/media/:mediaId/index',route(async(req,res)=>{const collection=find(req);findMedia(collection,req.params.mediaId);index(collection.id,req.params.mediaId);res.json(store.getCollection(collection.id).mediaIndex[req.params.mediaId]);}));
  app.get('/api/collections/:cid/media-search',route(async(req,res)=>{const collection=find(req);res.json(await searchMedia(collection,cfolder(collection.id),String(req.query.q||'')));}));
  for(const [action,operation] of [['clean-cut',(cid,mediaId,body)=>cleanCut(cstore,cid,cfolder(cid),mediaId,{minSilence:Number(body.minSilence)||0.45,removeFillers:body.removeFillers!==false})],['remove-background',(cid,mediaId)=>removeBackground(cstore,cid,cfolder(cid),mediaId)],['beats',(cid,mediaId)=>detectBeats(store.getCollection(cid),cfolder(cid),mediaId)]])
    app.post(`/api/collections/:cid/media/:mediaId/${action}`,route(async(req,res)=>{find(req);const result=await operation(req.params.cid,req.params.mediaId,req.body||{});if(result.asset){const collection=store.getCollection(req.params.cid);collection.assets=collection.assets.map(asset=>asset.id===result.asset.id?{...asset,origin:'derived'}:asset);store.saveCollection(collection);await sync(req.params.cid);}res.json(result);}));
  app.delete('/api/collections/:cid/library/:mediaId',route(async(req,res)=>{const collection=find(req),asset=(collection.assets||[]).find(item=>item.id===req.params.mediaId);if(!asset)throw new Error('Recurso inexistente.');collection.assets=collection.assets.filter(item=>item.id!==asset.id);if(collection.mediaIndex)delete collection.mediaIndex[asset.id];store.saveCollection(collection);store.db.prepare('DELETE FROM knowledge_search WHERE id IN (SELECT id FROM knowledge WHERE project_id=? AND source_id=?)').run('lib:'+collection.id,asset.id);store.db.prepare('DELETE FROM knowledge WHERE project_id=? AND source_id=?').run('lib:'+collection.id,asset.id);await rm(path.join(cfolder(collection.id),asset.path),{force:true});await rm(indexDirectory(cfolder(collection.id),asset.id),{recursive:true,force:true});await sync(collection.id);res.json({deleted:true});}));
  app.delete('/api/collections/:cid/media/:mediaId',route(async(req,res)=>{const collection=find(req),asset=(collection.assets||[]).find(item=>item.id===req.params.mediaId);if(!asset)throw new Error('Material inexistente.');collection.assets=collection.assets.filter(item=>item.id!==asset.id);if(collection.mediaIndex)delete collection.mediaIndex[asset.id];store.saveCollection(collection);await rm(path.join(cfolder(collection.id),asset.path),{force:true});await rm(indexDirectory(cfolder(collection.id),asset.id),{recursive:true,force:true});await sync(collection.id);res.json({deleted:true});}));
  app.get('/api/collections/:cid/files/*file',route(async(req,res)=>{find(req);const rootFolder=path.resolve(cfolder(req.params.cid)),file=path.resolve(rootFolder,[].concat(req.params.file).join('/'));if(!file.startsWith(rootFolder+path.sep))throw Object.assign(new Error('Ruta no permitida.'),{status:403});res.sendFile(file,{dotfiles:'allow'});}));
  // Fuentes de conocimiento comunes: se incorporan a cada vídeo nuevo del proyecto.
  app.put('/api/collections/:cid/sources',route(async(req,res)=>{const collection=find(req),sources=req.body?.sources;if(!Array.isArray(sources)||sources.length>10||sources.some(source=>typeof source?.name!=='string'||typeof source?.content!=='string'||!source.content.trim()||source.content.length>100000))throw new Error('Máximo 10 fuentes con nombre y contenido (100.000 caracteres cada una).');collection.sources=sources.map(({name,content})=>({name:name.slice(0,200),content}));store.saveCollection(collection);res.json(collection);}));
  // ---------- Agentes de proyecto y kit ----------
  app.post('/api/collections/:cid/agents/:kind',route(async(req,res)=>{find(req);const body=req.body||{},kind=req.params.kind;
    if(kind==='creative-director')return res.json(agents.creative(req.params.cid,{brief:String(body.brief||'').slice(0,8000),createVideos:body.createVideos===true,applyIdentity:body.applyIdentity===true}));
    if(kind==='kit-designer'){if(body.engine&&!KIT_ENGINES.includes(body.engine))throw new Error('Motor del kit inválido.');if(body.mode&&!['change','add','improve','remove'].includes(body.mode))throw new Error('Operación del kit inválida.');return res.json(agents.kit(req.params.cid,{instruction:String(body.instruction||'').slice(0,4000),engine:body.engine,mode:body.mode||'change',component:body.component?{name:String(body.component.name||'').slice(0,80),description:String(body.component.description||'').slice(0,2000)}:null}));}
    if(kind==='librarian')return res.json(agents.librarian(req.params.cid));
    throw new Error('Agente de proyecto desconocido.');}));
  app.delete('/api/collections/:cid/agents/:kind',route(async(req,res)=>{find(req);if(req.params.kind==='kit-designer'&&!req.query?.engine)return res.json({stopped:KIT_ENGINES.map(engine=>agents.stop(req.params.cid,'kit-designer:'+engine).stopped).some(Boolean)});res.json(agents.stop(req.params.cid,req.params.kind==='kit-designer'?'kit-designer:'+kitEngine(req,find(req)):req.params.kind));}));
  // Motor del kit pedido (query o cuerpo); por defecto, el único kit que exista o HyperFrames.
  const kitEngine=(req,collection)=>{const asked=req.body?.engine||req.query?.engine;if(asked){if(!KIT_ENGINES.includes(asked))throw new Error('Motor del kit inválido.');return asked;}const existing=Object.keys(kitsOf(collection));return existing.length===1?existing[0]:'hyperframes';};
  app.get('/api/hyperframes/catalog',route(async(req,res)=>{const {loadCatalog,rolesOf,ROLES}=await import('./hyperframes-catalog.mjs');const items=await loadCatalog(store,{refresh:req.query.refresh==='1'});const {REMOTION_RECIPES}=await import('./remotion-recipes.mjs');res.json({roles:ROLES.map(({id,label})=>({id,label})),items:items.map(item=>({...item,roles:rolesOf(item)})),recipes:REMOTION_RECIPES});}));
  // Datos del kit de un motor (archivos, capturas, historial, vídeos desactualizados y uso de componentes).
  async function kitData(collection,engine){const kit=kitOf(collection,engine),kits=kitsOf(collection),dir=kitDir(store,collection.id,engine),files=[];
    for(const file of await sourceFiles(dir)){if(file.startsWith('vendor/')||file==='gsap.min.js')continue;const info=await statFile(path.join(dir,file));files.push({path:file,size:info.size,content:info.size<200000?await readFile(path.join(dir,file),'utf8'):null});}
    let snapshots=[];try{const runs=(await readdir(path.join(dir,'snapshots'))).sort().reverse();if(runs[0])snapshots=(await readdir(path.join(dir,'snapshots',runs[0]))).filter(file=>file.endsWith('.png')).map(file=>`code/kit-${engine}/snapshots/${runs[0]}/${file}`);}catch{}
    const videos=store.list().filter(video=>video.collectionId===collection.id),stale=kit?.version?videos.filter(video=>video.tasks.some(task=>task.kind==='scene-code'&&task.output&&task.output.kitVersion!==kit.version&&video.storyboard?.scenes.find(scene=>scene.id===task.sceneId)?.engine===engine)).map(video=>({videoId:video.id,title:video.title})):[];
    return {engine,kit,usage:componentUsage(store,collection.id,engine),kits:Object.fromEntries(KIT_ENGINES.map(item=>[item,kits[item]?{status:kits[item].status,components:kits[item].components?.length||0,version:kits[item].version}:null])),runs:Object.fromEntries(KIT_ENGINES.map(item=>[item,collection.agentRuns?.['kit-designer:'+item]?.status||null])),run:collection.agentRuns?.['kit-designer:'+engine]||null,files,history:await listHistory(dir),snapshots,stale};}
  app.get('/api/collections/:cid/kit',route(async(req,res)=>{const collection=migrateKits(store,find(req));res.json(await kitData(collection,kitEngine(req,collection)));}));
  // Vista única del kit: componentes, capturas, archivos e historial de todos los motores juntos.
  app.get('/api/collections/:cid/kit/all',route(async(req,res)=>{const collection=migrateKits(store,find(req)),parts=[];
    for(const engine of KIT_ENGINES){const data=await kitData(collection,engine);if(data.kit||data.files.length||collection.agentRuns?.['kit-designer:'+engine])parts.push(data);}
    const runs=parts.map(part=>({engine:part.engine,...(collection.agentRuns?.['kit-designer:'+part.engine]||{})})).filter(run=>run.status);
    const stale=[];for(const part of parts)for(const video of part.stale)if(!stale.some(item=>item.videoId===video.videoId))stale.push(video);
    const ready=parts.filter(part=>part.kit?.status==='ready');
    res.json({ready:ready.length>0,engines:ready.map(part=>part.engine),components:ready.flatMap(part=>(part.kit.components||[]).map(item=>({...item,engine:part.engine}))),
      usage:Object.fromEntries(parts.flatMap(part=>Object.entries(part.usage).map(([name,count])=>[part.engine+'::'+name,count]))),
      updatedAt:ready.map(part=>part.kit.updatedAt).filter(Boolean).sort().at(-1)||null,version:ready.map(part=>part.kit.version.slice(0,6)).join('·'),
      snapshots:parts.flatMap(part=>part.snapshots),files:parts.flatMap(part=>part.files.map(file=>({...file,path:part.engine+'/'+file.path,engine:part.engine,file:file.path}))),
      history:parts.flatMap(part=>part.history.map(item=>({...item,engine:part.engine}))).sort((a,b)=>String(b.at).localeCompare(String(a.at))),
      stale,busy:runs.some(run=>run.status==='running'),runs,partial:parts.some(part=>!part.kit&&part.files.length)});}));
  // Peticiones al kit sin elegir motor: Lumen decide dónde va cada componente.
  app.post('/api/collections/:cid/kit/request',route(async(req,res)=>{const collection=migrateKits(store,find(req)),body=req.body||{},kits=kitsOf(collection);
    const readyEngines=KIT_ENGINES.filter(engine=>kits[engine]?.status==='ready'),preferred=readyEngines.sort((a,b)=>(kits[b].components?.length||0)-(kits[a].components?.length||0))[0]||effectiveSettings(collection).values.renderer||'remotion';
    const instruction=String(body.instruction||'').slice(0,4000),hint=KIT_ENGINES.includes(body.engine)?body.engine:null;
    if(body.mode==='add'){const name=String(body.component?.name||'').trim().slice(0,80);if(name.length<2)throw new Error('Indica el nombre del componente.');const engine=hint||preferred;
      const origin=body.component?.origin&&['own','catalog','recipe','exemplar'].includes(body.component.origin.kind)?{kind:body.component.origin.kind,ref:String(body.component.origin.ref||'').slice(0,120)||null,license:String(body.component.origin.license||'').slice(0,80)||null,url:String(body.component.origin.url||'').slice(0,300)||null}:null;
      agents.ensureComponent(collection.id,engine,{name,description:String(body.component?.description||'').slice(0,2000),origin}).catch(()=>{});return res.json({status:'running',engine});}
    if(['improve','remove'].includes(body.mode)){if(!hint)throw new Error('Falta el componente.');return res.json(agents.kit(collection.id,{engine:hint,mode:body.mode,instruction,component:{name:String(body.component?.name||'').slice(0,80)}}));}
    // Cambio general: a todos los kits existentes; si no hay ninguno, se crea en el motor por defecto del proyecto.
    const targets=readyEngines.length?readyEngines:[hint||preferred],started=[];
    for(const engine of targets){try{agents.kit(collection.id,{engine,instruction});started.push(engine);}catch(error){if(targets.length===1)throw error;}}
    res.json({status:'running',engines:started});}));
  app.post('/api/collections/:cid/kit/snapshot',route(async(req,res)=>{const collection=find(req);const {kitBriefFor}=await import('./collection-agents.mjs');const {dir,brief}=kitBriefFor(store,collection,kitEngine(req,collection));const frames=await snapshotScene(dir,brief,Array.isArray(req.body?.at)?req.body.at.map(Number):[1,3,5,7],AbortSignal.timeout(900000));res.json(frames.map(frame=>({time:frame.time,path:path.relative(cfolder(collection.id),frame.path).replaceAll('\\','/')})));}));
  app.post('/api/collections/:cid/kit/restore',route(async(req,res)=>{const collection=migrateKits(store,find(req)),engine=kitEngine(req,collection),dir=kitDir(store,collection.id,engine),{kitBriefFor}=await import('./collection-agents.mjs');const meta=await restoreHistory(dir,String(req.body?.historyId||''));const lint=await lintScene(dir,kitBriefFor(store,collection,engine).brief);if(!lint.ok)throw new Error('La versión restaurada no supera el lint.');collection.kits={...kitsOf(collection),[engine]:{...kitOf(collection,engine),engine,version:await sourceHash(dir),historyId:meta.id,updatedAt:new Date().toISOString()}};store.saveCollection(collection);res.json(collection.kits[engine]);}));
  app.put('/api/collections/:cid/kit/file',route(async(req,res)=>{const collection=migrateKits(store,find(req)),engine=kitEngine(req,collection);if(collection.agentRuns?.['kit-designer:'+engine]?.status==='running')throw new Error('Espera a que termine el diseñador del kit.');const {kitBriefFor}=await import('./collection-agents.mjs');const {dir,brief}=kitBriefFor(store,collection,engine);const file=await writeSourceFile(dir,req.body?.path,req.body?.content);const lint=await lintScene(dir,brief);
    if(lint.ok&&kitOf(collection,engine)?.status==='ready'){await snapshotSources(dir,'Editado a mano '+file);const latest=store.getCollection(collection.id);latest.kits={...kitsOf(latest),[engine]:{...kitOf(latest,engine),version:await sourceHash(dir),updatedAt:new Date().toISOString(),editedByHand:true}};store.saveCollection(latest);}
    res.json({file,lint});}));
  app.post('/api/collections/:cid/style-reference',route(async(req,res)=>{const collection=find(req),asset=(collection.assets||[]).find(item=>item.id===req.body?.assetId&&item.kind==='video');if(!asset)throw new Error('Elige un vídeo de la biblioteca del proyecto.');
    res.json(agents.start(collection.id,'style-reference',async()=>{const {analyzeReference,referenceBrief}=await import('./style-reference.mjs'),dir=path.join(cfolder(collection.id),'reference');await rm(dir,{recursive:true,force:true});
      const {spec,files}=await analyzeReference(path.join(cfolder(collection.id),asset.path),dir);const latest=store.getCollection(collection.id);latest.styleReference={status:'ready',assetId:asset.id,name:asset.name,analyzedAt:new Date().toISOString(),spec,files,brief:referenceBrief(asset.name,spec)};store.saveCollection(latest);
      return {summary:`Referencia analizada: ${spec.shots.count} planos, ${spec.pace} cambios cada 10 s.`};}));}));
  app.delete('/api/collections/:cid/style-reference',route(async(req,res)=>{const collection=find(req);collection.styleReference=null;store.saveCollection(collection);await rm(path.join(cfolder(collection.id),'reference'),{recursive:true,force:true});res.json({ok:true});}));
  app.post('/api/collections/:cid/style-frames',route(async(req,res)=>{const collection=find(req),asset=(collection.assets||[]).find(item=>item.id===req.body?.assetId&&item.kind==='image');if(!asset)throw new Error('Elige una imagen de la biblioteca del proyecto.');const name='lib-'+randomUUID().slice(0,8)+path.extname(asset.path);await mkdir(path.join(cfolder(collection.id),'style-frames'),{recursive:true});const {copyFile}=await import('node:fs/promises');await copyFile(path.join(cfolder(collection.id),asset.path),path.join(cfolder(collection.id),'style-frames',name));collection.styleFrames=[...(collection.styleFrames||[]),{id:randomUUID(),file:name,source:'library',note:asset.name}].slice(-8);store.saveCollection(collection);res.json(collection.styleFrames);}));
  app.delete('/api/collections/:cid/style-frames/:frameId',route(async(req,res)=>{const collection=find(req),frame=(collection.styleFrames||[]).find(item=>item.id===req.params.frameId);if(!frame)throw new Error('Fotograma inexistente.');collection.styleFrames=collection.styleFrames.filter(item=>item.id!==frame.id);store.saveCollection(collection);await rm(path.join(cfolder(collection.id),'style-frames',frame.file),{force:true});res.json(collection.styleFrames);}));
  app.delete('/api/collections/:cid/exemplars/:exemplarId',route(async(req,res)=>{const collection=find(req);collection.exemplars=(collection.exemplars||[]).filter(item=>item.id!==req.params.exemplarId);store.saveCollection(collection);await rm(path.join(cfolder(collection.id),'exemplars',path.basename(req.params.exemplarId)),{recursive:true,force:true});res.json(collection.exemplars);}));
  app.post('/api/collections/:cid/exemplars/:exemplarId/to-kit',route(async(req,res)=>{const collection=find(req),exemplar=(collection.exemplars||[]).find(item=>item.id===req.params.exemplarId);if(!exemplar)throw new Error('Ejemplo inexistente.');res.json(agents.kit(collection.id,{engine:exemplar.engine,exemplarId:exemplar.id,instruction:`Convierte la escena aprobada «${exemplar.title}» (en lumen/references/${exemplar.id}/) en uno o varios componentes parametrizados del kit, reutilizables en otras escenas, y documéntalos en KIT.md. Conserva el resto del kit. ${String(req.body?.instruction||'')}`}));}));
  app.post('/api/collections/:cid/kit/apply',route(async(req,res)=>{const collection=find(req),results=[];for(const video of store.list().filter(item=>item.collectionId===collection.id)){if(harness.active.has(video.id)){results.push({videoId:video.id,skipped:'en producción'});continue;}try{results.push({videoId:video.id,...await harness.applyKit(video.id)});}catch(error){results.push({videoId:video.id,error:error.message});}}res.json({results});}));
  app.get('/api/collections/:cid/activity',route(async(req,res)=>{find(req);res.json(store.events(req.params.cid).filter(event=>event.type==='agent.activity').slice(-80));}));
  app.post('/api/assist',route(async(req,res)=>{const {suggest}=await import('./assist.mjs');res.json(await suggest(store,harness,req.body||{}));}));
  app.post('/api/collections/:cid/copilot',route(async(req,res)=>{find(req);res.json(agents.copilot(req.params.cid,{request:String(req.body?.request||'').slice(0,4000)}));}));
  app.post('/api/collections/:cid/copilot/apply',route(async(req,res)=>{find(req);res.json(await agents.applyProposal(req.params.cid,String(req.body?.proposalId||''),{createVideos:req.body?.createVideos!==false,videos:req.body?.videos}));}));
  app.post('/api/collections/:cid/copilot/discard',route(async(req,res)=>{const collection=find(req);delete collection.copilotProposal;store.saveCollection(collection);res.json({discarded:true});}));
  // Proyecto nuevo a partir de una idea: se crea y la IA propone y aplica todo lo demás.
  app.post('/api/collections/ai',route(async(req,res)=>{const idea=String(req.body?.idea||'').trim();if(idea.length<10)throw new Error('Describe la idea con al menos 10 caracteres.');const runtime=['claude','codex','demo'].includes(req.body?.runtime)?req.body.runtime:'claude';
    const collection=createCollection(store,{name:idea.split(/[.,;:\n]/)[0].slice(0,60)||'Proyecto nuevo',objective:idea.slice(0,4000),settings:{runtime}},validateSettings);
    agents.copilot(collection.id,{request:`Prepara el proyecto completo a partir de esta idea: «${idea}». Propón nombre, objetivo, audiencia, guía de estilo, reglas, identidad visual (paleta, tipografía, intensidad), voz, subtítulos, formato${req.body?.series?' y una primera serie de vídeos con su encargo':''}.`,autoApply:true,createVideos:Boolean(req.body?.series)});
    res.status(201).json(store.getCollection(collection.id));}));
  app.get('/api/agent-models',(req,res)=>res.json(availableModels()));
  app.get('/api/agent-presets/:runtime/:preset',(req,res)=>{if(!['claude','codex'].includes(req.params.runtime))return res.status(400).json({error:'Runtime inválido.'});res.json(agentPreset(req.params.runtime,req.params.preset));});
  app.get('/api/collections',(req,res)=>res.json(store.collections().map(summary)));
  app.post('/api/collections',route(async(req,res)=>res.status(201).json(createCollection(store,req.body||{},validateSettings))));
  app.get('/api/collections/:cid',route(async(req,res)=>{const collection=find(req);res.json({...summary(collection),effective:effectiveSettings(collection),stale:staleVideos(store,collection).map(({values,...item})=>item)});}));
  app.patch('/api/collections/:cid',route(async(req,res)=>{find(req);const collection=updateCollection(store,req.params.cid,req.body||{},validateSettings);res.json({...summary(collection),effective:effectiveSettings(collection),stale:staleVideos(store,collection).map(({values,...item})=>item)});}));
  app.delete('/api/collections/:cid',route(async(req,res)=>{const collection=find(req),videos=store.list().filter(video=>video.collectionId===collection.id);if(videos.some(video=>harness.active.has(video.id)))throw new Error('Detén los vídeos en producción antes de borrar el proyecto.');for(const video of videos)await removeVideo(video.id);store.deleteCollection(collection.id);const folder=path.resolve(store.root,'collections',collection.id);if(folder.startsWith(path.resolve(store.root,'collections')+path.sep))await rm(folder,{recursive:true,force:true});res.json({deleted:true,videos:videos.length});}));
  app.get('/api/collections/:cid/videos',route(async(req,res)=>{find(req);res.json(store.list().filter(video=>video.collectionId===req.params.cid));}));
  app.post('/api/collections/:cid/videos',route(async(req,res)=>{find(req);const {prompt,duration,sources=[],overrides={}}=req.body||{};for(const key of Object.keys(overrides))if(!INHERITED_KEYS.includes(key))throw new Error('Ajuste no heredable: '+key);res.status(201).json(await harness.create({prompt,duration,sources,collectionId:req.params.cid,overrides}));}));
  // Aplica los ajustes actuales del proyecto a los vídeos elegidos (o a todos los desactualizados).
  app.post('/api/collections/:cid/apply',route(async(req,res)=>{const collection=find(req),stale=staleVideos(store,collection),ids=Array.isArray(req.body?.videoIds)?req.body.videoIds:stale.map(item=>item.videoId),results=[];for(const id of ids){const video=store.get(id);if(!video||video.collectionId!==collection.id)continue;if(harness.active.has(id)){results.push({videoId:id,skipped:'en producción'});continue;}await harness.applyInheritance(id);results.push({videoId:id,applied:true});}res.json({results,stale:staleVideos(store,collection).map(({values,...item})=>item)});}));
  app.get('/api/projects/:id/inheritance',route(async(req,res)=>{const video=store.get(req.params.id);if(!video)throw Object.assign(new Error('Vídeo inexistente.'),{status:404});const collection=video.collectionId&&store.getCollection(video.collectionId);if(!collection)return res.json({collection:null});const {values,origins}=effectiveSettings(collection,video.overrides||{});res.json({collection:{id:collection.id,name:collection.name},overrides:video.overrides||{},values,origins,stale:INHERITED_KEYS.filter(key=>stable(values[key])!==stable(video[key]))});}));
  app.put('/api/projects/:id/overrides',route(async(req,res)=>res.json(await harness.setOverrides(req.params.id,req.body?.overrides||{}))));
  app.delete('/api/projects/:id',route(async(req,res)=>{if(!store.get(req.params.id))throw Object.assign(new Error('Vídeo inexistente.'),{status:404});await removeVideo(req.params.id);res.json({deleted:true});}));
}
