import {spawn} from 'node:child_process';
import {writeFile,stat} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import ffmpeg from 'ffmpeg-static';
import {execute} from './process.mjs';
const script=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../scripts/loopback.ps1');
export async function audioCaptureReady(){try{await stat(path.join(process.env.LUMEN_TOOLS_DIR||path.resolve(path.dirname(script),'../.tools'),'audio/naudio.wasapi/lib/netstandard2.0/NAudio.Wasapi.dll'));return true;}catch{return false;}}
export async function startLoopback(output,seconds){const wav=output+'.wav',stopFile=output+'.stop',child=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',script,'-Output',wav,'-StopFile',stopFile,'-Seconds',String(seconds+30)],{windowsHide:true,stdio:['ignore','pipe','pipe']});let stderr='',buffer='',resolveReady,rejectReady;const ready=new Promise((resolve,reject)=>{resolveReady=resolve;rejectReady=reject;});child.stdout.on('data',data=>{buffer+=data;try{const value=JSON.parse(buffer.trim());if(value.ready)resolveReady(value);}catch{}});child.stderr.on('data',data=>stderr+=data);const completion=new Promise(resolve=>{child.on('error',error=>{rejectReady(error);resolve(-1);});child.on('close',code=>{if(code!==0)rejectReady(new Error(stderr.slice(-900)));resolve(code);});});const timer=setTimeout(()=>rejectReady(new Error('La captura WASAPI no respondió.')),30000);try{const status=await ready;return {wav,stopFile,child,completion,startedAt:status.startedAt};}catch(error){child.kill();throw error;}finally{clearTimeout(timer);}}
export async function finishLoopback(audio,video,startedAt){await writeFile(audio.stopFile,'stop');const timer=setTimeout(()=>audio.child.kill(),10000);const code=await audio.completion;clearTimeout(timer);if(code!==0)throw new Error('La captura de audio no terminó correctamente.');const offset=Math.max(0,(Date.parse(startedAt)-Date.parse(audio.startedAt))/1000),output=video+'.audio.mp4';const mixed=await execute(ffmpeg,['-y','-v','error','-i',video,'-ss',String(offset),'-i',audio.wav,'-map','0:v','-map','1:a','-af','apad','-shortest','-c:v','copy','-c:a','aac','-movflags','+faststart',output],{timeout:120000});if(mixed.code!==0)throw new Error('No se pudo añadir el audio del sistema.');const {rename}=await import('node:fs/promises');await rename(output,video);}
