  const parts=['voice','visual','captions'];
export function defaultProductionPlan(project,storyboardId){
  const tasks=[];for(const scene of project.storyboard.scenes){
    const voice=`voice-${scene.id}`,visual=`visual-${scene.id}`,captions=`captions-${scene.id}`;
    tasks.push({id:voice,kind:'voice',sceneId:scene.id,role:'narrador',label:`Voz · ${scene.title}`,instruction:'Generar narración aceptada',providerId:null,dependencies:[storyboardId]},{id:visual,kind:'visual',sceneId:scene.id,role:'artista',label:`Imagen · ${scene.title}`,instruction:'Preparar el recurso elegido',providerId:null,dependencies:[storyboardId,...(scene.type==='screencast'?project.tasks.filter(task=>task.kind==='screencast').map(task=>task.id):[])]},{id:captions,kind:'captions',sceneId:scene.id,role:'subtitulador',label:`Subtítulos · ${scene.title}`,instruction:'Alinear subtítulos con voz',providerId:null,dependencies:[voice]},{id:`media-${scene.id}`,kind:'scene',sceneId:scene.id,role:'montador',label:`Componer · ${scene.title}`,instruction:'Componer los recursos aceptados',providerId:null,dependencies:[voice,visual,captions]});
  }
  tasks.push({id:'render',kind:'render',sceneId:null,role:'editor',label:'Renderizar vídeo',instruction:'Renderizar segmentos y montar el MP4',providerId:null,dependencies:[...project.storyboard.scenes.map(scene=>`media-${scene.id}`),...project.tasks.filter(task=>task.kind==='review').map(task=>task.id)]},{id:'technical-review',kind:'technical-review',sceneId:null,role:'revisor técnico',label:'Revisar imagen y archivo',instruction:'Analizar MP4 y muestras visuales',providerId:null,dependencies:['render']});
  if(project.options?.audioReview)tasks.push({id:'audio-review',kind:'audio-review',sceneId:null,role:'revisor de audio',label:'Escuchar mediante transcripción',instruction:'Transcribir audio real y contrastar con el guion',providerId:null,dependencies:['render']});
  if(project.options?.finalReview&&project.runtime!=='demo')tasks.push({id:'final-review',kind:'final-review',sceneId:null,role:'revisor',label:'Revisión final',instruction:'Contrastar fuentes, imágenes, transcripción real y subtítulos',providerId:null,dependencies:['technical-review',...(project.options?.audioReview?['audio-review']:[])]});
  return {reasoning:'Voz e imagen en paralelo; subtítulos después de la voz. Revisiones tras el render.',tasks};
}
export function validateProductionPlan(value,project){
  const ids=new Set(),external=new Set(project.tasks.filter(task=>!['production-plan',...parts,'scene','render','technical-review','audio-review','final-review'].includes(task.kind)).map(task=>task.id));
  for(const task of value.tasks){if(ids.has(task.id)||external.has(task.id)||task.id==='production-director')throw new Error('Tareas de producción duplicadas o reservadas.');ids.add(task.id);if(task.sceneId&&!project.storyboard.scenes.some(scene=>scene.id===task.sceneId))throw new Error('Escena desconocida en producción.');if([...parts,'scene'].includes(task.kind)&&!task.sceneId)throw new Error('El recurso debe indicar una escena.');if(task.kind==='scene'&&task.id!==`media-${task.sceneId}`)throw new Error('La composición debe usar media-<escena>.');if(['render','technical-review','audio-review','final-review'].includes(task.kind)&&task.id!==task.kind)throw new Error('Identificador de etapa de producción inválido.');if(['render','technical-review','audio-review','final-review'].includes(task.kind)&&task.sceneId)throw new Error('Una etapa global no debe indicar una escena.');if(task.kind==='audio-review'&&!project.options?.audioReview||task.kind==='final-review'&&!project.options?.finalReview)throw new Error('El plan incluye una revisión desactivada.');if(task.providerId&&!['voice','visual'].includes(task.kind))throw new Error('Solo voz e imagen pueden elegir proveedor.');if(task.providerId&&project.availableProviders){const provider=project.availableProviders.find(item=>item.id===task.providerId);if(!provider||task.kind==='voice'&&provider.kind!=='voice'||task.kind==='visual'&&!['image','video','stock'].includes(provider.kind))throw new Error('El tipo del proveedor no corresponde al recurso.');}if(task.providerId&&(!project.options?.externalMedia||!project.availableProviderIds?.includes(task.providerId)))throw new Error('El director eligió un proveedor no disponible.');}
  const visiting=new Set(),visited=new Set();const visit=id=>{if(external.has(id))return;if(visiting.has(id))throw new Error('Producción cíclica.');if(visited.has(id))return;const task=value.tasks.find(item=>item.id===id);if(!task)throw new Error('Dependencia de producción inexistente.');visiting.add(id);for(const dep of task.dependencies)visit(dep);visiting.delete(id);visited.add(id);};for(const task of value.tasks)visit(task.id);
  const reaches=(id,target,seen=new Set())=>{if(id===target)return true;if(seen.has(id))return false;seen.add(id);return value.tasks.find(task=>task.id===id)?.dependencies.some(dep=>reaches(dep,target,seen))||false;};
  const board=project.tasks.find(task=>task.kind==='storyboard');for(const scene of project.storyboard.scenes){for(const part of [...parts,'scene']){const found=value.tasks.filter(task=>task.kind===part&&task.sceneId===scene.id);if(found.length!==1)throw new Error(`Producción requiere un ${part} para ${scene.id}.`);if(!reaches(found[0].id,board.id))throw new Error('Los recursos deben depender del storyboard.');}const voice=value.tasks.find(task=>task.kind==='voice'&&task.sceneId===scene.id),caps=value.tasks.find(task=>task.kind==='captions'&&task.sceneId===scene.id);if(!reaches(caps.id,voice.id))throw new Error('Subtítulos deben esperar a la voz.');for(const part of parts)if(!reaches(`media-${scene.id}`,value.tasks.find(task=>task.kind===part&&task.sceneId===scene.id).id))throw new Error('Composición sin todos los recursos.');if(!reaches('render',`media-${scene.id}`))throw new Error('Render sin todas las escenas.');}
  for(const task of project.tasks.filter(task=>task.kind==='review'))if(!reaches('render',task.id))throw new Error('El render debe esperar la revisión de contenido.');
  for(const kind of ['render','technical-review',...(project.options?.audioReview?['audio-review']:[]),...(project.options?.finalReview&&project.runtime!=='demo'?['final-review']:[])])if(value.tasks.filter(task=>task.kind===kind).length!==1)throw new Error(`Falta la etapa ${kind}.`);
  for(const kind of ['technical-review','audio-review'])if(value.tasks.some(task=>task.kind===kind)&&!reaches(kind,'render'))throw new Error('La revisión debe esperar al MP4.');
  if(ids.has('final-review')&&!['technical-review',...(project.options?.audioReview?['audio-review']:[])].every(id=>reaches('final-review',id)))throw new Error('La revisión final debe esperar todos los análisis.');return value;
}
