import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import {createCanvas} from '@napi-rs/canvas';
import {extractDocument} from '../server/knowledge.mjs';
import {producePart} from '../server/media-parts.mjs';
import {transcribeAudio,wordErrorRate} from '../server/audio-review.mjs';
import {startLoopback} from '../server/loopback.mjs';
import {execute} from '../server/process.mjs';
const folder=path.resolve(`.data/verification/infrastructure-${Date.now()}`);await mkdir(folder,{recursive:true});
function scannedPdf(jpeg,width,height){const objects=[Buffer.from('<< /Type /Catalog /Pages 2 0 R >>'),Buffer.from('<< /Type /Pages /Kids [3 0 R] /Count 1 >>'),Buffer.from('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 750 225] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>'),Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`),jpeg,Buffer.from('\nendstream')]),Buffer.from('<< /Length 31 >>\nstream\nq 750 0 0 225 0 0 cm /Im0 Do Q\nendstream')],parts=[Buffer.from('%PDF-1.4\n')],offsets=[0];for(const [index,object] of objects.entries()){offsets.push(Buffer.concat(parts).length);parts.push(Buffer.from(`${index+1} 0 obj\n`),object,Buffer.from('\nendobj\n'));}const start=Buffer.concat(parts).length;parts.push(Buffer.from(`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(offset=>String(offset).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer << /Size 6 /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`));return Buffer.concat(parts);}
const canvas=createCanvas(1500,450),ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,1500,450);ctx.fillStyle='black';ctx.font='52px Arial';ctx.fillText('DHCP asigna direcciones IP automaticamente.',70,150);ctx.fillText('El servidor configura los equipos de la red.',70,245);
const pdf=scannedPdf(canvas.toBuffer('image/jpeg'),1500,450);await writeFile(path.join(folder,'scanned.pdf'),pdf);const extracted=await extractDocument({name:'scanned.pdf',base64:pdf.toString('base64')});assert.match(extracted.content,/DHCP/i);assert.match(extracted.content,/OCR/);await writeFile(path.join(folder,'ocr.json'),JSON.stringify(extracted,null,2));console.log('PASS · OCR de PDF sin capa de texto.');
const project={id:'infra',runtime:'demo',recordings:[],profile:{},options:{},storyboard:{scenes:[{id:'s1',title:'Redes',narration:'El servidor configura automáticamente los equipos de la red. Cada equipo recibe una dirección.',duration:10,type:'diagram',points:['Servidor','Equipo']}]},tasks:[]};const voice=await producePart(project,'s1','voice',folder,new AbortController().signal),reused=await producePart(project,'s1','voice',folder,new AbortController().signal);assert.equal(reused.reused,true);assert.equal(voice.audioPath,reused.audioPath);const recognized=await transcribeAudio(path.join(folder,voice.audioPath),path.join(folder,'recognized'),new AbortController().signal);assert.ok(recognized.text.length>20);console.log('PASS · ASR local del audio real.',wordErrorRate(project.storyboard.scenes[0].narration,recognized.text));
if(process.argv.includes('--audio')){const audio=await startLoopback(path.join(folder,'loopback'),5);const playback=await execute('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-Command',"Add-Type -AssemblyName System; $player=New-Object System.Media.SoundPlayer; $player.SoundLocation=$env:LUMEN_TEST_AUDIO; $player.PlaySync();"],{env:{...process.env,LUMEN_TEST_AUDIO:path.join(folder,voice.audioPath)},timeout:30000});assert.equal(playback.code,0,playback.stderr);await writeFile(audio.stopFile,'stop');assert.equal(await audio.completion,0);assert.ok((await readFile(audio.wav)).length>1000);console.log('PASS · Captura WASAPI de sonido real con WAV válido.');}
