import {test,expect} from '@playwright/test';
import path from 'node:path';
import {mkdir,readFile,rm} from 'node:fs/promises';
import ffmpeg from 'ffmpeg-static';
import {execute} from '../../server/process.mjs';
test('corta recursos, compone varias capas y guarda tiempos y geometría desde la interfaz',async({page,request})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const response=await request.post('/api/projects',{data:{prompt:'Vídeo dinámico de DHCP con varios fragmentos de recursos.',duration:15,runtime:'demo',architecture:'tools',context:'minimal',style:'technology',concurrency:2,desktop:false,sources:[],options:{approvalGates:true,autonomousProduction:false,webResearch:false,externalMedia:false,finalReview:false,audioReview:false}}});expect(response.ok()).toBe(true);const project=await response.json();expect(project.profile.visualIntensity).toBe('cinematic');
  await request.post('/api/projects/'+project.id+'/run');await expect.poll(async()=>{const p=await (await request.get('/api/projects/'+project.id)).json();return p.status;}).toBe('needs-approval');
  for(let i=0;i<2;i++){await request.post('/api/projects/'+project.id+'/stage/approve');await expect.poll(async()=>{const p=await (await request.get('/api/projects/'+project.id)).json();return p.status;}).toBe('needs-approval');}
  let current=await (await request.get('/api/projects/'+project.id)).json();expect(current.storyboard).toBeTruthy();
  const root=path.resolve('.data/verification'),source=path.join(root,'ui-clips-'+Date.now()+'.mp4');await mkdir(root,{recursive:true});const generated=await execute(ffmpeg,['-y','-v','error','-f','lavfi','-i','testsrc2=s=320x180:r=24:d=4','-c:v','libx264','-pix_fmt','yuv420p',source]);expect(generated.code).toBe(0);
  try{const uploaded=await request.post('/api/projects/'+project.id+'/assets',{data:{name:'Recurso para montaje.mp4',base64:(await readFile(source)).toString('base64')}});expect(uploaded.ok()).toBe(true);}finally{expect(path.resolve(source).startsWith(root+path.sep)).toBe(true);await rm(source,{force:true});}
  await page.goto('/');await page.locator('[data-project-id="'+project.id+'"]').click();await page.getByRole('button',{name:'Más',exact:true}).click();await page.getByRole('button',{name:'Recursos web',exact:true}).click();await page.getByRole('button',{name:'Usar fragmento',exact:true}).click();
  await page.getByLabel('Inicio en el recurso (s)').fill('1');await page.getByLabel('Final en el recurso (s)').fill('3');await page.getByLabel('Aparece en la escena (s)').fill('1');await page.getByLabel('Velocidad del fragmento').fill('2');await page.getByRole('button',{name:'Insertar fragmento',exact:true}).click();
  await expect.poll(async()=>{const p=await (await request.get('/api/projects/'+project.id)).json();return p.storyboard.scenes[0].composition?.layers.some(layer=>layer.type==='media'&&layer.media?.from===1);}).toBe(true);
  current=await (await request.get('/api/projects/'+project.id)).json();const inserted=current.storyboard.scenes[0].composition.layers.find(layer=>layer.type==='media');expect(inserted.media).toMatchObject({from:1,to:3,rate:2});expect(inserted.start).toBe(1);expect(inserted.duration).toBe(1);await expect(page.locator('.resource-used')).toBeVisible();
  await page.getByRole('button',{name:'Usar fragmento',exact:true}).click();await page.getByLabel('Inicio en el recurso (s)').fill('0');await page.getByLabel('Final en el recurso (s)').fill('1');await page.getByLabel('Aparece en la escena (s)').fill('3');await page.getByLabel('Velocidad del fragmento').fill('1');await page.getByRole('button',{name:'Insertar fragmento',exact:true}).click();
  await expect.poll(async()=>{const p=await (await request.get('/api/projects/'+project.id)).json();return p.storyboard.scenes[0].composition.layers.filter(layer=>layer.type==='media').length;}).toBe(2);
  await page.getByRole('button',{name:'Más',exact:true}).click();await page.getByRole('button',{name:'Diseño y capas',exact:true}).click();await expect(page.getByRole('heading',{name:'Diseña con capas y ritmo'})).toBeVisible();await expect(page.getByLabel('Complejidad visual')).toHaveValue('cinematic');
  await page.locator('.design-add').getByRole('button',{name:'Texto',exact:true}).click();await page.getByLabel('Texto de la capa').fill('Texto superpuesto al montaje');await page.getByLabel('Entrada en escena (s)').fill('2');await page.getByLabel('Posición Y (%)').fill('72');await page.getByLabel('Altura (%)').fill('8');await page.getByLabel('Animación de la capa').selectOption('wipe');await page.getByRole('button',{name:'Guardar composición',exact:true}).click();
  await expect.poll(async()=>{const p=await (await request.get('/api/projects/'+project.id)).json();return p.storyboard.scenes[0].composition.layers.find(layer=>layer.text==='Texto superpuesto al montaje')?.motion;}).toBe('wipe');
  await page.locator('.design-json summary').click();const graph=JSON.parse(await page.getByLabel('Composición JSON').inputValue());const text=graph.layers.find(layer=>layer.text==='Texto superpuesto al montaje');text.keyframes=[{time:2,x:0,y:2,scale:.9,rotation:0,opacity:0},{time:2.6,x:0,y:0,scale:1,rotation:0,opacity:1},{time:5,x:2,y:0,scale:1.05,rotation:1,opacity:1}];await page.getByLabel('Composición JSON').fill(JSON.stringify(graph));await page.getByRole('button',{name:'Aplicar a la vista previa'}).click();await page.getByRole('button',{name:'Guardar composición',exact:true}).click();await expect.poll(async()=>{const p=await (await request.get('/api/projects/'+project.id)).json();return p.storyboard.scenes[0].composition.layers.find(layer=>layer.text==='Texto superpuesto al montaje')?.keyframes.length;}).toBe(3);await page.locator('.design-json summary').click();
  await page.screenshot({path:'.data/verification/design-ui.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.data/verification/design-ui-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Más',exact:true}).click();await page.getByRole('button',{name:'Recursos web',exact:true}).click();await page.getByRole('button',{name:'Descartar',exact:true}).click();await expect.poll(async()=>{const p=await (await request.get('/api/projects/'+project.id)).json();return p.storyboard.scenes[0].composition.layers.filter(layer=>layer.type==='media').length;}).toBe(0);
  expect(errors).toEqual([]);
});
