import {test,expect} from '@playwright/test';
import {createCanvas} from '@napi-rs/canvas';

test('Recursos reúne medios y páginas, permite seleccionar y asignar, y supervisa etapas',async({page,request})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const created=await request.post('/api/projects',{data:{prompt:'Prueba de recursos y supervisión de un vídeo sobre DHCP.',duration:15,runtime:'demo',architecture:'tools',context:'minimal',style:'editorial',concurrency:2,desktop:false,sources:[],options:{approvalGates:true,webResearch:false,externalMedia:false,autonomousProduction:false,audioReview:false,finalReview:false}}});expect(created.ok()).toBe(true);const project=await created.json();
  const canvas=createCanvas(800,450),ctx=canvas.getContext('2d');ctx.fillStyle='#eae3ff';ctx.fillRect(0,0,800,450);ctx.fillStyle='#5c478f';ctx.font='bold 42px sans-serif';ctx.fillText('CLIENTE DHCP',70,190);ctx.font='30px sans-serif';ctx.fillText('Solicitud de dirección IP',70,260);
  const upload=await request.post(`/api/projects/${project.id}/assets`,{data:{name:'Diagrama del cliente.png',base64:canvas.toBuffer('image/png').toString('base64')}});expect(upload.ok()).toBe(true);
  await page.goto('/');await page.locator(`[data-project-id="${project.id}"]`).click();await expect(page.getByLabel('Modo de ejecución',{exact:true})).toHaveValue('supervised');await page.getByRole('button',{name:'Más',exact:true}).click();await page.getByRole('button',{name:'Recursos web',exact:true}).click();await expect(page.getByRole('heading',{name:'Recursos para tu historia'})).toBeVisible();await expect(page.locator('.resource-card img')).toBeVisible();await expect(page.getByText('Licencia no indicada',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Seleccionar',exact:true}).click();await expect(page.getByText('Seleccionado',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Valorar imágenes y vídeos',exact:true}).click();await expect.poll(async()=>{const current=await (await request.get(`/api/projects/${project.id}`)).json();return current.resources?.[0]?.assessment?.inspected;},{timeout:30000}).toBe(false);
  await expect(page.getByText('Esta etapa espera tu revisión')).toBeVisible();await page.locator('.resource-assessment summary').click();await expect(page.getByText('El modo demo no dispone de visión ni realiza una valoración real.')).toBeVisible();await page.screenshot({path:'.data/verification/resources.png',fullPage:true});
  await page.getByRole('button',{name:'Aprobar etapa y continuar',exact:true}).click();await expect.poll(async()=>{const current=await (await request.get(`/api/projects/${project.id}`)).json();return current.status==='needs-approval'&&current.tasks.find(task=>task.kind==='research')?.status==='completed';},{timeout:30000}).toBe(true);
  let current=await (await request.get(`/api/projects/${project.id}`)).json();expect(current.tasks.find(task=>task.kind==='script').status).toBe('pending');expect(current.resources.some(resource=>resource.kind==='page'&&resource.name.includes('RFC'))).toBe(true);
  await page.getByRole('button',{name:/Páginas/}).click();await expect(page.getByText('Referencia sin consultar',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Abrir procedencia'})).toHaveAttribute('href','https://www.rfc-editor.org/rfc/rfc2131');
  await page.getByRole('button',{name:'Revisar etapa',exact:true}).click();await expect(page.getByRole('heading',{name:'Revisar cada etapa'})).toBeVisible();await expect(page.getByText('Plan del director y dependencias')).toBeVisible();await page.getByRole('button',{name:'Aprobar etapa y continuar',exact:true}).click();await expect.poll(async()=>{const p=await (await request.get(`/api/projects/${project.id}`)).json();return p.status==='needs-approval'&&p.tasks.find(task=>task.kind==='script')?.status==='completed';},{timeout:30000}).toBe(true);
  await page.getByRole('button',{name:'Aprobar etapa y continuar',exact:true}).click();await expect.poll(async()=>{const p=await (await request.get(`/api/projects/${project.id}`)).json();return p.status==='needs-approval'&&!!p.storyboard;},{timeout:30000}).toBe(true);
  current=await (await request.get(`/api/projects/${project.id}`)).json();await page.getByRole('button',{name:'Más',exact:true}).click();await page.getByRole('button',{name:'Recursos web',exact:true}).click();await page.getByRole('button',{name:/Imágenes/}).click();await page.getByLabel('Escena para Diagrama del cliente.png').selectOption(current.storyboard.scenes[0].id);await page.getByRole('button',{name:'Usar',exact:true}).click();await expect.poll(async()=>(await (await request.get(`/api/projects/${project.id}`)).json()).storyboard.scenes[0].visual?.assetId).toBe(current.assets[0].id);await expect(page.locator('.resource-used')).toBeVisible();
  await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'.data/verification/resources-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Descartar',exact:true}).click();await expect.poll(async()=>(await (await request.get(`/api/projects/${project.id}`)).json()).storyboard.scenes[0].visual?.assetId).toBe(null);await expect(page.getByRole('button',{name:'Usar',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Recuperar',exact:true}).click();await page.getByLabel('Escena para Diagrama del cliente.png').selectOption(current.storyboard.scenes[0].id);await page.getByRole('button',{name:'Usar',exact:true}).click();
  const accepted=(await (await request.get(`/api/projects/${project.id}`)).json()).tasks.find(task=>task.kind==='research').completedAt;
  await page.getByLabel('Modo de ejecución',{exact:true}).selectOption('automatic');await expect.poll(async()=>(await (await request.get(`/api/projects/${project.id}`)).json()).options.approvalGates).toBe(false);await expect(page.getByText('Esta etapa espera tu revisión')).toHaveCount(0);
  await page.getByRole('button',{name:'Continuar producción',exact:true}).click();await expect.poll(async()=>{const p=await (await request.get(`/api/projects/${project.id}`,{timeout:120000})).json();if(p.status==='failed')throw new Error(p.error);return p.status;},{timeout:600000,intervals:[1000,3000,5000]}).toBe('completed');
  const rendered=await (await request.get(`/api/projects/${project.id}`)).json();expect(rendered.render.size).toBeGreaterThan(10000);expect(rendered.tasks.find(task=>task.kind==='scene'&&task.sceneId===current.storyboard.scenes[0].id).output.visualPath).toBe(current.assets[0].path);expect(rendered.tasks.find(task=>task.kind==='research').completedAt).toBe(accepted);expect(rendered.technicalReview.approved).toBe(true);expect(errors).toEqual([]);
});
