import React,{useState,useEffect,useCallback} from 'react';
import {Player} from '@remotion/player';
import {LayoutGrid,Clapperboard,Workflow,FolderOpen,FlaskConical,Plug,Plus,ArrowUpRight,ArrowLeft,ArrowRight,Search,ChevronDown,Check,Clock,Play,Pause,Download,MoreHorizontal,Layers,Sparkles,Monitor,Film,Volume2,FileText,Network,ShieldCheck,Activity,X,Upload,Settings2,Grid2X2,List,Square,Camera,CheckCircle2,AlertCircle,LoaderCircle,ExternalLink,Copy,MousePointer2,BookOpen,Zap,Link2,Terminal,RefreshCw} from 'lucide-react';
import {DesignStudio} from './DesignStudio.jsx';
import {previewMedia} from './video/design-preview.mjs';
import {LumenVideo} from './video/Composition.jsx';
import {SharedLibrary,LocalTools,CompletionProject} from './CompletionStudio.jsx';
import {outputSpec} from './video/output.mjs';
import {ProductionOptions,ProjectStudio,ProviderSettings,ExperimentLab,documentSource} from './StudioExtensions.jsx';
import {ResourceLibrary,ExecutionMode,SupervisionPanel,StageApprovals} from './ResourceLibrary.jsx';
import {studioApi} from './studio-api.mjs';
import {useAutosave,SaveStatus} from './autosave.jsx';
import {CollectionsHome,CollectionView} from './CollectionStudio.jsx';
const labels={draft:'Borrador',planning:'Planificando',running:'En producción',paused:'En pausa',failed:'Requiere atención',completed:'Listo para revisar',approved:'Aprobado','needs-review':'Revisión pendiente','needs-approval':'Espera aprobación'};
const roleInfo=[['director','Director','Diseña el plan y coordina el equipo.',Workflow],['investigador','Investigador','Reúne fuentes y verifica conceptos.',BookOpen],['guionista','Guionista','Da estructura y voz a tu historia.',FileText],['storyboard','Diseñador de escenas','Transforma el guion en una secuencia visual.',Layers],['revisor','Revisor de contenido','Comprueba claridad y rigor.',ShieldCheck],['producción','Producción audiovisual','Prepara las escenas y la narración.',Clapperboard],['operador','Operador del PC','Graba demostraciones en tu escritorio.',MousePointer2],['editor','Editor','Compone el vídeo final con Remotion.',Film]];
const formatDuration=seconds=>`${Math.floor(seconds/60)}:${String(Math.round(seconds%60)).padStart(2,'0')}`;
const when=date=>new Intl.DateTimeFormat('es',{day:'numeric',month:'short'}).format(new Date(date));
const running=project=>['planning','running','rendering'].includes(project?.status);
async function api(url,options={}){const response=await fetch(`/api${url}`,{...options,headers:{'Content-Type':'application/json',...options.headers},...(options.body?{body:JSON.stringify(options.body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error||'No se ha podido completar la acción.');return data;}
function saveJson(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Badge({project}){return <span className={`badge status-${project.status}`}>{running(project)?<span className="live-dot"/>:project.status==='approved'?<Check size={11}/>:null}{project.example?'Ejemplo · storyboard':labels[project.status]||project.status}</span>;}
function Thumbnail({project,scene,large=false}){const first=scene||project.storyboard?.scenes?.[0];return <div className={`thumbnail theme-${project.style} ${large?'large':''}`}><span className="thumb-grid"/><span className="thumb-orbit"/><div className="thumb-kicker">{first?.eyebrow||'TU PRÓXIMA HISTORIA'}</div><div className="thumb-title">{first?.title||project.title}</div><div className="thumb-diagram"><span><Monitor size={large?26:20}/></span><i/><span><Network size={large?26:20}/></span><i/><span><Layers size={large?26:20}/></span></div><div className="thumb-footer"><span>lumen studio</span><span>{first?formatDuration(first.duration):formatDuration(project.duration)}</span></div></div>;}
function Empty({icon:Icon=FolderOpen,title,text,action}){return <div className="empty"><div className="empty-icon"><Icon size={25}/></div><h3>{title}</h3><p>{text}</p>{action}</div>;}
export default function App(){
  const [collectionId,setCollectionId]=useState(null),[collections,setCollections]=useState([]);
  const [page,setPage]=useState('projects'),[projects,setProjects]=useState([]),[health,setHealth]=useState(null),[selected,setSelected]=useState(null),[modal,setModal]=useState(false),[toast,setToast]=useState(null),[search,setSearch]=useState(''),[loading,setLoading]=useState(true);
  const notify=useCallback((message,error=false)=>{setToast({message,error});},[]);
  const refresh=useCallback(async()=>{try{const [data,list]=await Promise.all([api('/projects'),api('/collections')]);setProjects(data);setCollections(list);setLoading(false);}catch(error){notify(error.message,true);}},[notify]);
  useEffect(()=>{refresh();api('/health').then(setHealth).catch(error=>notify(error.message,true));const events=new EventSource('/api/live');let timer;events.onmessage=()=>{clearTimeout(timer);timer=setTimeout(refresh,150);};const interval=setInterval(()=>api('/health').then(setHealth).catch(()=>{}),15000);return()=>{events.close();clearTimeout(timer);clearInterval(interval);};},[refresh,notify]);
  useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(null),5000);return()=>clearTimeout(timer);}},[toast]);
  const current=projects.find(project=>project.id===selected);
  const navigate=key=>{setSelected(null);setCollectionId(null);setPage(key);setSearch('');};
  const act=async(fn)=>{try{const result=await fn();await refresh();api('/health').then(setHealth).catch(()=>{});return result;}catch(error){notify(error.message,true);return null;}};
  const active=projects.filter(running).length;
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="#" onClick={event=>{event.preventDefault();navigate('projects');}}><span className="brand-symbol"><Clapperboard size={21}/></span>lumen<span className="brand-period">.</span></a><span className="workspace-label">TU ESPACIO CREATIVO</span><nav>{[['projects','Proyectos',LayoutGrid],['agents','Agentes',Workflow],['library','Biblioteca',FolderOpen],['lab','Laboratorio',FlaskConical]].map(([key,label,Icon])=><button key={key} className={`nav-item ${page===key?'active':''}`} onClick={()=>navigate(key)}><Icon size={18}/><span>{label}</span>{key==='projects'&&<span className="nav-count">{collections.length}</span>}{key==='agents'&&active>0&&<span className="nav-count">{active}</span>}</button>)}</nav><div className="sidebar-spacer"/><div className="local-note"><span className="green-dot"/><span>Tu estudio, en tu equipo</span><p>Proyectos y archivos guardados localmente.</p></div><button className={`nav-item ${page==='connections'?'active':''}`} onClick={()=>navigate('connections')}><Plug size={18}/><span>Conexiones</span></button><div className="profile"><div className="avatar">T</div><div><strong>Tu espacio personal</strong><span>Estudio local</span></div><span className="local-pill">LOCAL</span></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumbs"><span>Mi espacio</span><span>/</span><strong>{current?'Vídeo':collectionId&&page==='projects'?(collections.find(item=>item.id===collectionId)?.name||'Proyecto'):({projects:'Proyectos',agents:'Equipo de agentes',library:'Biblioteca',lab:'Laboratorio',connections:'Conexiones'})[page]}</strong></div><div className="topbar-right"><span className="engine-status"><span className={health?.runtimes.codex.authenticated||health?.runtimes.claude.authenticated?'green-dot':'gray-dot'}/>{health?`${Object.values(health.runtimes).filter((runtime,index)=>index<2&&runtime.authenticated).length} motores disponibles`:'Conectando…'}</span><button className="icon-button" aria-label="Ver conexiones" onClick={()=>navigate('connections')}><Settings2 size={18}/></button><div className="avatar small">T</div></div></header>
    <main>{current?<ProjectView project={current} health={health} onBack={()=>{setCollectionId(current.collectionId||null);setPage('projects');setSelected(null);}} act={act} notify={notify}/>:page==='projects'?(collectionId?<CollectionView collectionId={collectionId} videos={projects} onBack={()=>setCollectionId(null)} onOpenVideo={setSelected} act={act} notify={notify} documentSource={documentSource}/>:<CollectionsHome collections={collections} videos={projects} onOpen={setCollectionId} onOpenVideo={setSelected} act={act} notify={notify}/>):page==='agents'?<Agents projects={projects} onOpen={id=>{setPage('projects');setSelected(id);}}/>:page==='library'?<><Library projects={projects} onOpen={id=>{setPage('projects');setSelected(id);}}/><SharedLibrary projects={projects} notify={notify}/></>:page==='lab'?<><Lab projects={projects}/><ExperimentLab notify={notify}/></>:<><Connections health={health} notify={notify}/><ProviderSettings notify={notify}/><LocalTools notify={notify}/></>}</main><footer className="app-footer"><span><span className="tiny-brand">✦</span> Un espacio para ideas que merecen ser contadas.</span><span>Lumen Studio · v0.2</span></footer></div>
    {modal&&<CreateModal health={health} onClose={()=>setModal(false)} onCreate={async(input,start)=>{const project=await act(()=>api('/projects',{method:'POST',body:input}));if(project){setModal(false);setPage('projects');setSelected(project.id);if(start)await act(()=>api(`/projects/${project.id}/run`,{method:'POST'}));}}}/>}
    {toast&&<div role="status" className={`toast ${toast.error?'error':''}`}>{toast.error?<AlertCircle size={18}/>:<CheckCircle2 size={18}/>}<span>{toast.message}</span><button onClick={()=>setToast(null)} aria-label="Cerrar aviso"><X size={15}/></button></div>}
  </div>;
}
function Projects({projects,loading,onNew,onOpen,search,setSearch}){
  const [filter,setFilter]=useState('all'),[layout,setLayout]=useState('grid');
  const visible=projects.filter(project=>(filter==='all'||filter==='active'&&running(project)||filter==='done'&&['completed','approved'].includes(project.status))&&project.title.toLowerCase().includes(search.toLowerCase()));
  return <><div className="page-heading"><div><div className="eyebrow">DE LA IDEA A LA PANTALLA</div><h1>Tu estudio de vídeo<span className="heading-spark">✦</span></h1><p>Historias que enseñan. Un equipo que las hace realidad.</p></div><button className="button primary" onClick={onNew}><Plus size={18}/>Nuevo proyecto</button></div>
  <section className="hero"><div className="hero-content"><span className="hero-label"><Sparkles size={13}/> UN ESTUDIO QUE PIENSA CONTIGO</span><h2>Tú pones la idea.<br/>Tu equipo, el resto.</h2><p>Delega la investigación, el guion y las escenas.<br/>Sigue cada paso y dale tu toque final.</p><button className="button dark" onClick={onNew}>Crear mi primer vídeo<ArrowUpRight size={16}/></button></div><div className="hero-art" aria-hidden="true"><span className="hero-glow"/><div className="floating-chip chip-research"><span className="chip-icon mint"><BookOpen size={15}/></span><div><strong>Una buena historia</strong><small>empieza con una idea</small></div><CheckCircle2 size={15}/></div><div className="hero-film"><div className="film-top"><span className="mini-dots">● ● ●</span><span>YOUR NEXT BIG IDEA</span></div><div className="hero-film-main"><span className="film-star">✦</span><strong>Haz que<br/>se entienda.</strong><div className="film-play"><Play size={20} fill="currentColor"/></div></div><div className="film-bottom"><span/><span/><span/><span/><span/></div></div><div className="floating-chip chip-agents"><div className="chip-stack"><span>G</span><span>E</span><span>R</span></div><div><strong>Tu equipo creativo</strong><small>agentes especializados</small></div><Workflow size={16}/></div><span className="hero-little-star">✧</span></div></section>
  <div className="quick-stats"><div><span className="stat-icon lilac"><Clapperboard size={18}/></span><div><strong>{projects.length}<span> proyectos</span></strong><small>Ideas en tu estudio</small></div></div><div><span className="stat-icon peach"><Activity size={18}/></span><div><strong>{projects.filter(running).length}<span> en producción</span></strong><small>Tu equipo está trabajando</small></div></div><div><span className="stat-icon mint"><CheckCircle2 size={18}/></span><div><strong>{projects.filter(project=>['completed','approved'].includes(project.status)).length}<span> vídeos listos</span></strong><small>Preparados para revisar</small></div></div><div><span className="stat-icon blue"><Layers size={18}/></span><div><strong>{projects.reduce((sum,project)=>sum+(project.storyboard?.scenes.length||0),0)}<span> escenas</span></strong><small>Cada detalle cuenta</small></div></div></div>
  <div className="section-heading"><div><h2>Tus proyectos <span className="count-pill">{projects.length}</span></h2><p>Retoma una historia o empieza algo nuevo.</p></div><div className="project-tools"><label className="search-field"><Search size={16}/><input placeholder="Buscar proyectos…" value={search} onChange={event=>setSearch(event.target.value)} aria-label="Buscar proyectos"/></label><div className="view-switch"><button className={layout==='grid'?'selected':''} onClick={()=>setLayout('grid')} aria-label="Vista de tarjetas"><Grid2X2 size={17}/></button><button className={layout==='list'?'selected':''} onClick={()=>setLayout('list')} aria-label="Vista de lista"><List size={17}/></button></div></div></div>
  <div className="filter-tabs">{[['all','Todos'],['active','En producción'],['done','Terminados']].map(([key,label])=><button className={filter===key?'selected':''} key={key} onClick={()=>setFilter(key)}>{label}</button>)}</div>
  {loading?<div className="loading"><LoaderCircle className="spin"/>Abriendo tu estudio…</div>:<div className={`project-grid ${layout==='list'?'list-layout':''}`}>{visible.map(project=><button className="project-card" data-project-id={project.id} key={project.id} onClick={()=>onOpen(project.id)}><div className="card-preview"><Thumbnail project={project}/><span className="duration-pill"><Clock size={11}/>{formatDuration(project.render?.duration||project.duration)}</span><span className="card-hover"><ArrowUpRight size={24}/></span></div><div className="card-body"><div className="card-topline"><Badge project={project}/><MoreHorizontal size={17}/></div><h3>{project.title}</h3><p>{project.storyboard?.scenes.length||0} escenas <span>·</span> {project.runtime==='demo'?'Demo fija':project.runtime==='codex'?'Codex':'Claude Code'}</p><div className="card-bottom"><span className="runtime-symbol">{project.runtime==='codex'?'⌘':project.runtime==='claude'?'✳':'◈'}</span><span>{project.architecture==='single'?'Agente único':project.architecture==='tools'?'Agentes + skills + MCP':'Equipo de agentes'}</span><small>{when(project.updatedAt)}</small></div></div></button>)}{filter==='all'&&!search&&<button className="new-project-card" onClick={onNew}><span className="new-plus"><Plus size={24}/></span><h3>Tu próxima gran idea</h3><p>Un concepto, una explicación,<br/>una historia por contar.</p><span className="text-link">Crear proyecto <ArrowRight size={14}/></span></button>}</div>}
  {!loading&&!visible.length&&(filter!=='all'||search)&&<Empty icon={Search} title="Todavía no hay proyectos aquí" text="Prueba con otra búsqueda o crea una nueva historia."/>}
  <div className="bottom-tip"><span className="tip-icon"><Zap size={16}/></span><p><strong>Empieza con algo concreto.</strong> Un tema, una audiencia y una duración ayudan a tu equipo a acertar.</p><button onClick={onNew}>Probar una idea<ArrowRight size={14}/></button></div></>;
}
function CreateModal({health,onClose,onCreate}){
  const [input,setInput]=useState({prompt:'',duration:120,runtime:'codex',authoring:'code',architecture:'tools',context:'minimal',style:'editorial',concurrency:2,desktop:false,sources:[],renderer:'remotion',profile:{visualIntensity:'cinematic'},options:{finalReview:true,replan:true,persistent:false,approvalGates:false,externalMedia:false,webResearch:false}}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const key=event=>{if(event.key==='Escape'&&!busy)onClose();};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[onClose,busy]);
  const set=(key,value)=>setInput(previous=>({...previous,[key]:value}));
  const submit=async(start)=>{if(input.prompt.trim().length<10){setError('Describe tu vídeo con al menos 10 caracteres.');return;}setBusy(true);setError('');try{await onCreate(input,start);}catch(error){setError(error.message);}finally{setBusy(false);}};
  const files=async event=>{try{const sources=await Promise.all([...event.target.files].map(documentSource));set('sources',[...input.sources,...sources]);}catch(error){setError(error.message);}};
  const ready=input.runtime==='demo'||health?.runtimes[input.runtime]?.authenticated;
  return <div className="modal-backdrop" onClick={event=>{if(event.target===event.currentTarget&&!busy)onClose();}}><section className="create-modal" role="dialog" aria-modal="true" aria-labelledby="create-title"><div className="modal-heading"><span className="modal-icon"><Sparkles size={22}/></span><button className="icon-button" onClick={onClose} aria-label="Cerrar nuevo proyecto" disabled={busy}><X size={20}/></button></div><div className="eyebrow">EMPIEZA CON UNA IDEA</div><h2 id="create-title">¿Qué vamos a contar?</h2><p className="modal-intro">Dale un encargo a tu equipo. Tú marcas la dirección.</p><label className="field-label" htmlFor="prompt">Tu vídeo</label><textarea id="prompt" className="prompt-input" placeholder="Un anuncio de 30 segundos para una cafetería, un resumen de producto, un tutorial de software, un vídeo para redes…" value={input.prompt} onChange={event=>set('prompt',event.target.value)}/><div className="suggestion-chips">{[['Anuncio de producto','Crea un anuncio de 30 segundos para un producto, con un gancho en los primeros segundos y una llamada a la acción clara.'],['Vídeo para redes','Crea un vídeo vertical de 45 segundos para redes sociales, con ritmo rápido y subtítulos grandes.'],['Explicación de un tema','Crea un vídeo de 2 minutos que explique un tema de forma clara, con ejemplos concretos.'],['Una demostración en el PC','Crea un vídeo de 2 minutos con una demostración grabada en el PC.']].map(([topic,prompt])=><button key={topic} onClick={()=>{set('prompt',prompt);if(topic.includes('PC'))set('desktop',true);}}>{topic}<Plus size={12}/></button>)}</div>
  <div className="form-row"><label>Duración<select value={input.duration} onChange={event=>set('duration',Number(event.target.value))}>{[[15,'15 segundos'],[30,'30 segundos'],[60,'1 minuto'],[120,'2 minutos'],[180,'3 minutos'],[300,'5 minutos'],[600,'10 minutos']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Estilo visual<select value={input.style} onChange={event=>set('style',event.target.value)}><option value="editorial">Editorial · Lavanda</option><option value="technology">Tecnología · Oscuro</option><option value="whiteboard">Pizarra · Cálido</option><option value="documentary">Documental</option><option value="short">Short</option><option value="presentation">Presentación</option><option value="infographic">Infografía</option><option value="news">Noticias</option></select></label></div>
  <label className="field-label">Motor creativo</label><div className="runtime-options">{[['codex','Codex','⌘'],['claude','Claude Code','✳'],['demo','Demo','◈']].map(([key,label,symbol])=><button key={key} className={input.runtime===key?'selected':''} onClick={()=>set('runtime',key)}><span>{symbol}</span><strong>{label}</strong><small>{key==='demo'?'DHCP predefinido':health?.runtimes[key]?.authenticated?'Suscripción disponible':'Necesita iniciar sesión'}</small>{input.runtime===key&&<CheckCircle2 size={15}/>}</button>)}</div>
  <details className="advanced"><summary><Settings2 size={15}/>Equipo y ejecución<ChevronDown size={14}/></summary><div className="form-row"><label>Arquitectura<select value={input.architecture} onChange={event=>set('architecture',event.target.value)}><option value="single">A · Un agente</option><option value="multi">B · Agentes especializados</option><option value="tools">C · Agentes, skills y MCP</option></select></label><label>Contexto<select value={input.context} onChange={event=>set('context',event.target.value)}><option value="minimal">Solo lo necesario</option><option value="full">Contexto completo</option></select></label><label>Procesos paralelos<select value={input.concurrency} onChange={event=>set('concurrency',Number(event.target.value))}>{[1,2,3,4].map(number=><option key={number}>{number}</option>)}</select></label></div></details>
  <ProductionOptions input={input} set={set}/>
  <label className="desktop-toggle"><span className="stat-icon blue"><Monitor size={19}/></span><span><strong>Demostraciones en tu PC</strong><small>Permitir capturas, clics y grabación del escritorio.</small></span><input type="checkbox" checked={input.desktop} onChange={event=>set('desktop',event.target.checked)}/><span className="toggle-track"/></label>
  <label className="upload-zone"><Upload size={17}/><span>Añadir apuntes o fuentes <small>PDF, TXT, Markdown o JSON</small></span><input type="file" multiple accept=".pdf,.txt,.md,.json" onChange={files}/><Plus size={15}/></label>{input.sources.map((source,index)=><div className="source-chip" key={index}><FileText size={13}/>{source.name}<button aria-label={`Quitar ${source.name}`} onClick={()=>set('sources',input.sources.filter((_,position)=>position!==index))}><X size={13}/></button></div>)}
  {input.runtime==='demo'&&<p className="form-note">La demo usa contenido fijo de DHCP para probar el estudio. No consume cuota ni evalúa un modelo.</p>}{error&&<p className="inline-error" role="alert">{error}</p>}<div className="modal-footer"><button className="button secondary" disabled={busy} onClick={()=>submit(false)}>Guardar borrador</button><button className="button primary" disabled={busy||!ready} onClick={()=>submit(true)}>{busy?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>}Crear y generar</button></div></section></div>;
}
function ProjectView({project,health,onBack,act,notify}){
  const [systemAudio,setSystemAudio]=useState(false);const output=outputSpec(project.output);
  const [tab,setTab]=useState('scenes'),[moreTab,setMoreTab]=useState('storyboard'),[sceneId,setSceneId]=useState(null),[events,setEvents]=useState([]),[edit,setEdit]=useState(null),[screenshot,setScreenshot]=useState(null),[busy,setBusy]=useState(false),[sourceText,setSourceText]=useState('');
  const scenes=project.storyboard?.scenes||[],scene=scenes.find(item=>item.id===sceneId)||scenes[0];
  useEffect(()=>{if(scene)setEdit({...scene,pointsText:scene.points.join('\n')});},[scene?.id,scene?.title,scene?.narration,scene?.duration,scene?.type,JSON.stringify(scene?.points)]);
  useEffect(()=>{if(tab==='activity')api(`/projects/${project.id}/events`).then(setEvents).catch(()=>{});},[tab,project.updatedAt]);
  const action=async(fn)=>{setBusy(true);try{return await act(fn);}finally{setBusy(false);}};
  const post=(suffix,body)=>action(()=>api(`/projects/${project.id}/${suffix}`,{method:'POST',...(body?{body}:{})}));
  const preview=previewMedia(project);const totalFrames=scenes.reduce((sum,item)=>sum+Math.round((preview[item.id]?.duration||item.duration)*output.fps),0);
  const progress=project.tasks.length?Math.round(project.tasks.filter(task=>task.status==='completed').length/project.tasks.length*100):0;
  const recording=health?.desktop.recording?.projectId===project.id;
  const fileUrl=file=>`/api/projects/${project.id}/files/${file}`;
  return <><button className="back-link" onClick={onBack}><ArrowLeft size={16}/>Todos los proyectos</button><div className="page-heading project-heading"><div><div className="project-meta"><Badge project={project}/><span>{project.runtime==='demo'?'Demostración fija':project.runtime==='codex'?'Codex':'Claude Code'} · {formatDuration(project.duration)}</span></div><h1>{project.title}</h1><p>{project.architecture==='multi'?'Un equipo especializado para cada parte de tu historia.':'Un agente para dar forma a tu historia.'}</p></div><div className="heading-actions">{running(project)?<button className="button secondary" disabled={busy} onClick={()=>post('pause')}><Pause size={16}/>Pausar</button>:<button className="button primary" disabled={busy} onClick={()=>post('run')}><Play size={16}/>{project.tasks.length?'Continuar producción':'Generar vídeo'}</button>}<button className="icon-button bordered" onClick={()=>saveJson('project.json',project)} aria-label="Exportar proyecto JSON"><Download size={17}/></button></div></div>
  <ExecutionMode options={project.options} disabled={busy||running(project)} onChange={value=>act(()=>studioApi('/projects/'+project.id+'/config',{method:'PATCH',body:{options:{approvalGates:value}}}))}/>
  <SupervisionPanel project={project} act={act} onReview={()=>{setTab('more');setMoreTab('approvals');}}/>
  {project.desktop&&<div className="desktop-safety"><Monitor size={16}/><span>Control del PC activado para este proyecto</span><button className="button danger" onClick={()=>act(()=>api(`/projects/${project.id}/desktop/emergency-stop`,{method:'POST'}))}><Square size={13} fill="currentColor"/>Parada de emergencia</button></div>}
  <div className="project-workspace"><div className="project-main"><div className="video-preview">{project.render?<video controls src={fileUrl(project.render.path)} poster={undefined}/>:scenes.length?<Player key={project.updatedAt} component={LumenVideo} inputProps={{storyboard:project.storyboard,style:project.style,profile:project.profile,output:project.output,media:preview}} durationInFrames={totalFrames} initialFrame={Math.min(output.fps,totalFrames-1)} compositionWidth={output.width} compositionHeight={output.height} fps={output.fps} controls style={{width:'100%',aspectRatio:output.width+'/'+output.height}}/>:<div className="preview-placeholder"><Clapperboard size={45}/><h2>Tu historia empieza aquí</h2><p>El director preparará el guion y las escenas.</p></div>}</div><div className="preview-caption"><span><Film size={15}/>{project.render?'Vídeo renderizado':'Vista previa del storyboard'}</span><span>{scenes.length} escenas · {project.render?`${project.render.width}×${project.render.height} · ${project.render.fps} fps`:project.example?'Contenido de ejemplo':'Narración pendiente'}</span></div>
  {project.render&&<div className="review-banner"><span className="stat-icon mint"><ShieldCheck size={18}/></span><div><strong>{project.status==='approved'?'Vídeo aprobado':'Dale una última mirada'}</strong><p>Comprueba el contenido, el ritmo y los subtítulos.</p></div><a className="button secondary" href={`${fileUrl(project.render.path)}?download=1`}><Download size={15}/>MP4</a><button className="button primary" disabled={busy||project.status==='approved'} onClick={()=>post('approve')}><Check size={16}/>Aprobar</button></div>}
  {project.awaiting==='budget'&&<div className="review-banner budget-banner"><span className="stat-icon mint"><Clock size={18}/></span><div><strong>Se ha alcanzado el límite de gasto de este vídeo</strong><small>Los agentes se han detenido. Puedes ampliar el límite un 50 % y continuar, o cambiarlo en los ajustes del proyecto.</small></div><button className="button primary" onClick={()=>act(()=>studioApi(`/projects/${project.id}/budget/continue`,{method:'POST',body:{}}))}>Ampliar y continuar</button></div>}
  <div className="detail-tabs">{[['scenes','Escenas',Layers],['library','Biblioteca',FolderOpen],['edit','Montaje',Film],['settings','Ajustes',Settings2],['activity','Actividad',Activity],['more','Más',MoreHorizontal]].map(([key,label,Icon])=><button key={key} className={tab===key?'selected':''} onClick={()=>setTab(key)}><Icon size={15}/>{label}</button>)}</div>
  {tab==='more'&&<div className="studio-tabs more-tabs">{[['storyboard','Storyboard clásico',Layers],['script','Guion',FileText],['resources','Recursos web',FolderOpen],['design','Diseño y capas',Sparkles],['approvals','Revisión de etapas',ShieldCheck],['sources','Fuentes',BookOpen],['desktop','PC y grabaciones',Monitor],['studio','Producción avanzada',Settings2]].map(([key,label,Icon])=><button key={key} className={moreTab===key?'selected':''} onClick={()=>setMoreTab(key)}><Icon size={14}/>{label}</button>)}</div>}
  {tab==='scenes'&&<CompletionProject tab="code" project={project} act={act} notify={notify}/>}
  {tab==='library'&&<><CompletionProject tab="library" project={project} act={act} notify={notify}/><details className="more-details"><summary>Candidatos web y recursos de investigación</summary><ResourceLibrary project={project} act={act}/></details></>}
  {tab==='edit'&&<><CompletionProject tab="timeline" project={project} act={act} notify={notify}/><CompletionProject tab="components" project={project} act={act} notify={notify}/></>}
  {tab==='settings'&&<><CompletionProject tab="inheritance" project={project} act={act} notify={notify}/><details className="more-details"><summary>Opciones avanzadas: perfil, ejecución, versiones y aprobaciones</summary><ProjectStudio project={project} act={act} notify={notify}/></details></>}
  {tab==='activity'&&<Receipt project={project}/>}
  {tab==='activity'&&project.publication&&<Publication project={project} act={act}/>}
  {tab==='activity'&&<CompletionProject tab="jobs" project={project} act={act} notify={notify}/>}
  {tab==='more'&&moreTab==='design'&&<DesignStudio project={project} act={act}/>}
  {tab==='more'&&moreTab==='resources'&&<ResourceLibrary project={project} act={act}/>}
  {tab==='more'&&moreTab==='approvals'&&<StageApprovals project={project} act={act}/>}
  {tab==='more'&&moreTab==='studio'&&<ProjectStudio project={project} act={act} notify={notify}/>}
  {tab==='more'&&moreTab==='storyboard'&&(scenes.length?<><div className="scene-strip">{scenes.map((item,index)=><button key={item.id} className={scene?.id===item.id?'selected':''} onClick={()=>setSceneId(item.id)}><Thumbnail project={project} scene={item}/><span><strong>{String(index+1).padStart(2,'0')}</strong>{formatDuration(item.duration)}</span></button>)}</div>{edit&&<div className="scene-editor"><div className="section-heading"><h3>Escena {scenes.findIndex(item=>item.id===scene.id)+1} <span className="subtle">/ {scenes.length}</span></h3><button className="text-button" disabled={busy||running(project)||!project.tasks.length} onClick={()=>post('regenerate',{taskId:`media-${scene.id}`})}><RefreshCw size={14}/>Regenerar escena</button></div><div className="form-row"><label>Título<input value={edit.title} onChange={event=>setEdit({...edit,title:event.target.value})}/></label><label>Componente<select value={edit.type} onChange={event=>setEdit({...edit,type:event.target.value})}>{[['title','Título'],['diagram','Diagrama'],['comparison','Comparación'],['bullets','Conceptos'],['quote','Cita'],['screencast','Grabación del PC']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="duration-field">Duración (s)<input type="number" min="2" max="120" value={edit.duration} onChange={event=>setEdit({...edit,duration:Number(event.target.value)})}/></label></div><label className="field-label">Narración<textarea value={edit.narration} onChange={event=>setEdit({...edit,narration:event.target.value})}/></label><label className="field-label">Texto visual · una idea por línea<textarea rows={3} value={edit.pointsText} onChange={event=>setEdit({...edit,pointsText:event.target.value})}/></label><div className="editor-footer"><span>Se conservarán los recursos de las demás escenas.</span><button className="button secondary" disabled={busy||running(project)} onClick={()=>action(async()=>{const {pointsText,...changes}=edit;await api(`/projects/${project.id}/scenes/${scene.id}`,{method:'PATCH',body:{...changes,points:pointsText.split('\n').filter(Boolean)}});notify('Escena guardada. Puedes continuar la producción.');})}><Check size={15}/>Guardar cambios</button></div></div>}</>:<Empty icon={Layers} title="Cada escena, con una intención" text="Genera el proyecto para ver y editar su storyboard."/>)}
  {tab==='more'&&moreTab==='script'&&<div className="script-list">{scenes.length?scenes.map((item,index)=><article key={item.id}><span>{String(index+1).padStart(2,'0')}</span><div><h3>{item.title}<small>{formatDuration(item.duration)}</small></h3><p>{item.narration}</p></div></article>):<Empty icon={FileText} title="El guion está por escribir" text="Tu equipo lo preparará cuando generes el proyecto."/>}</div>}
  {tab==='more'&&moreTab==='sources'&&<div className="sources-panel"><h3>El conocimiento detrás del vídeo</h3><p className="subtle">Tus fuentes se incluyen en el trabajo de investigación.</p>{project.sources.map((source,index)=><details className="source-item" key={index}><summary><FileText size={17}/>{source.name}<ChevronDown size={15}/></summary><pre>{source.content}</pre></details>)}{project.tasks.filter(task=>task.kind==='research'&&task.output).flatMap(task=>task.output.sources).map((source,index)=><div className="source-item source-reference" key={`ref-${index}`}><BookOpen size={17}/><span>{source.title}</span>{/^https?:\/\//.test(source.url)&&<a href={source.url} target="_blank" rel="noreferrer" aria-label={`Abrir ${source.title}`}><ExternalLink size={15}/></a>}</div>)}<label className="field-label">Añadir una fuente o apuntes<textarea placeholder="Pega una referencia, un fragmento de apuntes o el contenido que deba seguir el vídeo." value={sourceText} onChange={event=>setSourceText(event.target.value)}/></label><button className="button secondary" disabled={busy||running(project)||!sourceText.trim()} onClick={()=>action(async()=>{await api(`/projects/${project.id}/sources`,{method:'PUT',body:{sources:[...project.sources,{name:`Apuntes ${project.sources.length+1}`,content:sourceText}]}});setSourceText('');notify('Fuente añadida. El director volverá a evaluar el plan.');})}><Plus size={15}/>Añadir fuente</button></div>}
  {tab==='activity'&&<div className="activity-list">{events.length?events.map(event=><div key={event.seq}><span className="event-dot"/><div><strong>{event.message||event.type}</strong><small>{event.taskId||'Proyecto'} · {new Date(event.at).toLocaleTimeString('es')}</small>{event.event&&<details><summary>Ver llamada de herramienta</summary><pre>{JSON.stringify(event.event,null,2)}</pre></details>}</div></div>):<Empty icon={Activity} title="Toda la historia de tu proyecto" text="Aquí aparecerán las decisiones, tareas y llamadas a herramientas."/>}</div>}
  {(tab==='more'&&moreTab==='desktop')&&<div className="desktop-panel"><label className="desktop-toggle"><span className="stat-icon blue"><Monitor size={19}/></span><span><strong>Control del PC por agentes</strong><small>Capturas, clics, teclado y grabación de la pantalla.</small></span><input type="checkbox" checked={project.desktop} onChange={event=>action(()=>api(`/projects/${project.id}/desktop`,{method:'PUT',body:{enabled:event.target.checked}}))}/><span className="toggle-track"/></label><div className="desktop-toolbar"><button className="button secondary" disabled={busy||!project.desktop} onClick={()=>action(async()=>{const result=await api(`/projects/${project.id}/desktop/screenshot`,{method:'POST',body:{}});setScreenshot(fileUrl(result.path));})}><Camera size={16}/>Capturar pantalla</button>{recording?<button className="button danger" disabled={busy} onClick={()=>post('stop-recording')}><Square size={14} fill="currentColor"/>Detener grabación</button>:<button className="button secondary" disabled={busy||!project.desktop||Boolean(health?.desktop.owner)} onClick={()=>post('desktop/start_recording',{seconds:120,systemAudio})}><span className="record-dot"/>Grabar escritorio</button>}</div><label className="desktop-audio"><input type="checkbox" checked={systemAudio} disabled={Boolean(recording)||busy} onChange={event=>setSystemAudio(event.target.checked)}/>Capturar también el sonido del PC</label><p className="form-note">El audio del sistema se captura con WASAPI. Un solo agente puede controlar el PC a la vez.</p>{screenshot&&<img className="screen-image" src={screenshot} alt="Última captura de tu escritorio"/>}{project.recordings.map(item=><div className="recording-card" key={item.id}>{item.status==='completed'?<video controls src={fileUrl(item.path)}/>:<p className="inline-error">{item.error}</p>}<span><Film size={15}/>{when(item.createdAt)} · Grabación del PC</span></div>)}</div>}
  </div><aside className="production-panel"><div className="panel-title"><span className="stat-icon lilac"><Workflow size={18}/></span><div><h3>Tu equipo en acción</h3><p>Todo conectado, paso a paso.</p></div></div><div className="production-progress"><span>Progreso del proyecto<strong>{progress}%</strong></span><div><i style={{width:`${progress}%`}}/></div></div>{project.tasks.length?<div className="task-list">{project.tasks.map(task=><div className={`task-item task-${task.status}`} key={task.id}><span className="task-status">{task.status==='completed'?<Check size={13}/>:task.status==='running'?<LoaderCircle size={13} className="spin"/>:task.status==='failed'?<AlertCircle size={13}/>:<span/>}</span><div><strong>{task.label}</strong><small>{task.role} {task.attempts>1?`· intento ${task.attempts}`:''}</small>{task.error&&<p>{task.error.slice(0,180)}</p>}</div></div>)}</div>:<div className="plan-pending"><Sparkles size={23}/><p>El director elegirá las tareas y los agentes al empezar.</p></div>}<div className="team-config"><span><Layers size={14}/>Contexto<strong>{project.context==='minimal'?'Mínimo':'Completo'}</strong></span><span><Zap size={14}/>Paralelismo<strong>{project.concurrency} procesos</strong></span><span><Monitor size={14}/>Control del PC<strong>{project.desktop?'Activado':'Desactivado'}</strong></span></div><div className="usage-box"><span>Consumo registrado</span><strong>{(project.metrics.inputTokens+project.metrics.outputTokens).toLocaleString('es')}<small> tokens</small></strong><p>{project.metrics.calls} llamadas completadas{project.metrics.unknownUsageCalls>0?' · hay consumo no informado':''}</p><small>La cuota de suscripción no se convierte directamente a tokens.</small></div>{project.error&&<div className="error-box"><AlertCircle size={17}/><p>{project.error}</p></div>}{project.review&&<div className="review-box"><strong><ShieldCheck size={15}/>Revisión de contenido</strong><p>{project.review.summary}</p>{project.review.issues.map((issue,index)=><p key={index} className="inline-error">{issue.message}</p>)}</div>}{project.technicalReview&&<div className="review-box"><strong><Film size={15}/>Revisión técnica</strong><p>{project.technicalReview.summary}</p>{project.technicalReview.issues.map((issue,index)=><p key={index}>{issue}</p>)}</div>}<button className="button secondary full-width" onClick={()=>saveJson('storyboard.json',project.storyboard||{})}><Download size={15}/>Exportar storyboard</button></aside></div></>;
}
function Agents({projects,onOpen}){return <><div className="page-heading"><div><div className="eyebrow">CADA TALENTO, SU FUNCIÓN</div><h1>Tu equipo de agentes</h1><p>Contexto propio, responsabilidades claras y trabajo en paralelo.</p></div></div><div className="agent-grid">{roleInfo.map(([role,title,description,Icon],index)=>{const tasks=projects.flatMap(project=>project.tasks.filter(task=>task.role===role).map(task=>({...task,project})));return <article className="agent-card" key={role}><div className="agent-top"><span className={`stat-icon ${['lilac','mint','peach','blue'][index%4]}`}><Icon size={23}/></span><span className="badge">{tasks.filter(task=>task.status==='running').length?'Trabajando':'Disponible'}</span></div><h3>{title}</h3><p>{description}</p><div className="agent-count"><span>{tasks.filter(task=>task.status==='completed').length} tareas completadas</span>{tasks.find(task=>task.status==='running')&&<button className="text-button" onClick={()=>onOpen(tasks.find(task=>task.status==='running').project.id)}>Ver tarea<ArrowUpRight size={14}/></button>}</div></article>;})}</div><div className="bottom-tip"><Workflow size={19}/><p>El director elige el equipo según el encargo. La producción y el render utilizan herramientas locales.</p></div></>;}
function Library({projects,onOpen}){const items=projects.flatMap(project=>(project.storyboard?.scenes||[]).map(scene=>({project,scene})));return <><div className="page-heading"><div><div className="eyebrow">PIEZAS DE TUS HISTORIAS</div><h1>Tu biblioteca visual</h1><p>Escenas y componentes de todos tus proyectos, en un solo lugar.</p></div><span className="badge">{items.length} escenas</span></div>{items.length?<div className="library-grid">{items.map(({project,scene})=><button className="library-card" key={`${project.id}-${scene.id}`} onClick={()=>onOpen(project.id)}><Thumbnail project={project} scene={scene}/><strong>{scene.title}</strong><span>{project.title} · {formatDuration(scene.duration)}</span></button>)}</div>:<Empty title="Tu biblioteca crecerá con cada historia" text="Los storyboards que generes aparecerán aquí."/>}</>;}
function Lab({projects}){const results=projects.filter(project=>project.metrics.calls>0);return <><div className="page-heading"><div><div className="eyebrow">PRUEBA, COMPARA, DECIDE</div><h1>Mide lo que importa</h1><p>Compara motores, arquitecturas y contexto con ejecuciones reales.</p></div><button className="button secondary" onClick={()=>saveJson('experiments.json',results.map(project=>({id:project.id,prompt:project.prompt,runtime:project.runtime,architecture:project.architecture,context:project.context,concurrency:project.concurrency,status:project.status,metrics:project.metrics,review:project.finalReview||project.review||project.technicalReview,wallTimeMs:project.wallTimeMs,renderer:project.renderer})))}><Download size={16}/>Exportar resultados</button></div><div className="lab-explanation"><FlaskConical size={26}/><div><h3>El mismo encargo. Distintas estrategias.</h3><p>Crea proyectos con el mismo prompt y cambia el motor, la arquitectura o el contexto. Las demos se identifican por separado y no representan rendimiento de un modelo.</p></div></div>{results.length?<div className="table-wrap"><table><thead><tr><th>Proyecto</th><th>Motor</th><th>Arquitectura</th><th>Contexto</th><th>Llamadas</th><th>Tokens</th><th>Tiempo de agentes</th></tr></thead><tbody>{results.map(project=><tr key={project.id}><td>{project.title}</td><td>{project.runtime==='demo'?'Demo fija':project.runtime}</td><td>{project.architecture==='single'?'Un agente':project.architecture==='tools'?'Agentes + skills + MCP':'Varios agentes'}</td><td>{project.context==='minimal'?'Mínimo':'Completo'}</td><td>{project.metrics.calls}</td><td>{(project.metrics.inputTokens+project.metrics.outputTokens).toLocaleString('es')}</td><td>{formatDuration(project.metrics.durationMs/1000)}</td></tr>)}</tbody></table></div>:<Empty icon={FlaskConical} title="Tu primer experimento está por llegar" text="Genera un proyecto para registrar tiempos, consumo y resultados."/>}<p className="form-note">El tiempo de agentes suma las llamadas completadas y puede superar el tiempo de pared cuando hay paralelismo. El consumo de intentos fallidos puede no estar informado.</p></>;}
function Connections({health,notify}){return <><div className="page-heading"><div><div className="eyebrow">LAS HERRAMIENTAS DE TU ESTUDIO</div><h1>Conexiones</h1><p>Motores locales, tu suscripción y herramientas para producir.</p></div></div><div className="connection-grid">{[['codex','Codex','⌘','codex login'],['claude','Claude Code','✳','claude auth login']].map(([key,title,symbol,command])=><article className="connection-card" key={key}><div className="connection-top"><span className={`connection-logo ${key}`}>{symbol}</span><span className={`badge ${health?.runtimes[key]?.authenticated?'connected':''}`}>{health?.runtimes[key]?.authenticated?'Sesión disponible':'Sin sesión'}</span></div><h3>{title}</h3><p>Integración mediante el CLI instalado en tu equipo. El SDK es opcional.</p><div className="connection-info"><span>Autenticación<strong>{health?.runtimes[key]?.authMethod||'Comprobando…'}</strong></span><span>CLI instalado<strong>{health?.runtimes[key]?.installed?'Sí':'No detectado'}</strong></span></div><button className="button secondary full-width" onClick={async()=>{await navigator.clipboard.writeText(command);notify('Comando copiado. Ejecútalo en tu terminal.');}}><Terminal size={15}/>{command}<Copy size={14}/></button></article>)}<article className="connection-card"><div className="connection-top"><span className="connection-logo local"><Monitor size={25}/></span><span className="badge">{health?.desktop.supported?'Windows disponible':'Requiere Windows'}</span></div><h3>Control y grabación del PC</h3><p>Los agentes pueden observar la pantalla, hacer clic, escribir y grabar demostraciones.</p><div className="connection-info"><span>Acceso<strong>Se activa por proyecto</strong></span><span>Escritorio<strong>{health?.desktop.owner?'Reservado':'Libre'}</strong></span></div><p className="form-note">La parada y la grabación manual están en la pestaña «PC y grabaciones» del proyecto.</p></article><article className="connection-card"><div className="connection-top"><span className="connection-logo media"><Clapperboard size={25}/></span><span className="badge">Herramientas locales</span></div><h3>Voz y producción</h3><p>Narración con voces de Windows, componentes audiovisuales y render con Remotion.</p><div className="connection-info"><span>Salida<strong>MP4 · 720p</strong></span><span>Subtítulos<strong>Temporización estimada</strong></span></div><p className="form-note">La narración requiere una voz española instalada. Los proveedores multimedia externos se incorporarán como adaptadores opcionales.</p></article></div></>;}

// Recibo del vídeo: petición literal, trabajo por rol, rondas de crítica y coste si hay precios configurados.
function Receipt({project}){
  const [data,setData]=useState(null);useEffect(()=>{api(`/projects/${project.id}/receipt`).then(setData).catch(()=>setData(null));},[project.updatedAt]);
  if(!data||!data.total.calls)return null;
  const tokens=value=>value>=1e6?(value/1e6).toFixed(2)+' M':value>=1e3?Math.round(value/1e3)+' k':String(value);
  return <section className="receipt"><h3>Recibo</h3><p className="form-note">Petición: «{data.request}»</p>
    <div className="receipt-totals"><div><strong>{data.total.calls}</strong><small>llamadas</small></div><div><strong>{tokens(data.total.inputTokens)}</strong><small>tokens de entrada ({tokens(data.total.cachedTokens)} en caché)</small></div><div><strong>{tokens(data.total.outputTokens)}</strong><small>tokens de salida</small></div><div><strong>{data.critic.rounds}</strong><small>rondas de crítica</small></div><div><strong>{data.cost?data.cost.amount.toFixed(2)+' $':'—'}</strong><small>{data.cost?(data.cost.complete?'coste mínimo estimado':'coste parcial: faltan precios'):'sin precios configurados'}</small></div></div>
    <table className="receipt-table"><thead><tr><th>Rol</th><th>Modelo</th><th>Llamadas</th><th>Entrada</th><th>Salida</th></tr></thead><tbody>{data.roles.map(role=><tr key={role.kind}><td>{role.name}</td><td>{role.model||'—'}{role.effort?' · '+role.effort:''}</td><td>{role.calls}</td><td>{tokens(role.inputTokens)}</td><td>{tokens(role.outputTokens)}</td></tr>)}</tbody></table>
    {data.critic.unverified>0&&<p className="code-error">{data.critic.unverified} escenas tuvieron un crítico que no demostró haber mirado las imágenes.</p>}
    {data.unknownUsageCalls>0&&<p className="form-note">{data.unknownUsageCalls} llamadas no informaron de su consumo: el total es un mínimo.</p>}
  </section>;
}

// Publicación del vídeo: propuesta del agente, editable y con autoguardado.
function Publication({project,act}){
  const fromProject=value=>({title:value.title||'',description:value.description||'',chapters:(value.chapters||[]).map(item=>`${Math.floor(item.time/60)}:${String(Math.floor(item.time%60)).padStart(2,'0')} ${item.title}`).join('\n'),tags:(value.tags||[]).join(', '),shareText:value.shareText||''});
  const [draft,setDraft]=useState(()=>fromProject(project.publication));
  const parse=value=>({title:value.title,description:value.description,shareText:value.shareText,tags:value.tags.split(',').map(tag=>tag.trim()).filter(Boolean),chapters:value.chapters.split('\n').map(line=>{const match=/^(\d+):(\d{1,2})\s+(.+)$/.exec(line.trim());return match?{time:Number(match[1])*60+Number(match[2]),title:match[3]}:null;}).filter(Boolean)});
  const {status}=useAutosave(draft,value=>studioApi(`/projects/${project.id}/publication`,{method:'PATCH',body:parse(value)}),{delay:1200});
  const copy=()=>{try{navigator.clipboard.writeText([draft.title,'',draft.description,'',draft.chapters,'',draft.tags].join('\n'));}catch{}};
  return <section className="receipt publication"><div className="panel-head"><h3>Publicación</h3><SaveStatus status={status}/></div>
    {project.publication.poster&&<img className="publication-poster" src={`/api/projects/${project.id}/files/${project.publication.poster}`} alt="Fotograma propuesto para la miniatura"/>}
    <label>Título<input value={draft.title} maxLength={100} onChange={event=>setDraft({...draft,title:event.target.value})}/></label>
    <label>Descripción<textarea rows={6} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></label>
    <label>Capítulos (uno por línea: minuto:segundo título)<textarea rows={5} value={draft.chapters} onChange={event=>setDraft({...draft,chapters:event.target.value})}/></label>
    <label>Etiquetas (separadas por comas)<input value={draft.tags} onChange={event=>setDraft({...draft,tags:event.target.value})}/></label>
    <label>Texto para compartir<input value={draft.shareText} maxLength={500} onChange={event=>setDraft({...draft,shareText:event.target.value})}/></label>
    <button className="button secondary" onClick={copy}>Copiar título, descripción y capítulos</button>
  </section>;
}
