import React,{useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowDown,GripVertical,Check,RefreshCw,BookOpen,Library,Volume2,Download,Plug,Monitor,Play,Save} from 'lucide-react';
import './completion-studio.css';
import {CodeScenes} from './CodeStudio.jsx';
import {LibraryPanel} from './LibraryPanel.jsx';
import {useAutosave,SaveStatus} from './autosave.jsx';
import {uploadFile} from './studio-api.mjs';
import {InheritancePanel} from './CollectionStudio.jsx';
import {Code2,Film,Layers} from 'lucide-react';
async function api(url,options={}){const response=await fetch('/api'+url,{...options,headers:{'Content-Type':'application/json'},...(options.body?{body:JSON.stringify(options.body)}:{})});const value=await response.json();if(!response.ok)throw new Error(value.error);return value;}
const post=(url,body={})=>api(url,{method:'POST',body});
const active=project=>['running','planning','rendering'].includes(project.status);
export const completionTabs=[['inheritance','Heredado del proyecto',Layers],['code','Escenas',Code2],['library','Biblioteca',Film],['timeline','Timeline',Play],['components','Voz y subtítulos',Volume2],['shared','Biblioteca compartida',Library],['jobs','Solicitudes externas',RefreshCw]];
export function CompletionProject({tab,project,act,notify}){
  const [busy,setBusy]=useState(false);const run=async fn=>{setBusy(true);try{await act(fn);}finally{setBusy(false);}};const props={project,run,busy:busy||active(project),notify};
  return <>{tab==='inheritance'&&<InheritancePanel project={project} act={act} notify={notify}/>} {tab==='code'&&<CodeScenes project={project} act={act} notify={notify}/>} {tab==='library'&&<LibraryPanel title="Biblioteca del vídeo" act={act} notify={notify} owner={{base:`/projects/${project.id}`,target:{videoId:project.id},fileUrl:value=>`/api/projects/${project.id}/files/${value}`,upload:(item,role)=>uploadFile(project.id,item,role),research:{url:`/projects/${project.id}/library/research`,run:project.libraryResearch},active:active(project),note:project.collectionId?'Recursos de este vídeo más los del proyecto (marcados «del proyecto»). Lo que subas aquí solo lo verá este vídeo.':'Recursos de este vídeo: imágenes, vídeos, audio, documentos y datos.'}}/>} {tab==='timeline'&&<Timeline {...props}/>} {tab==='components'&&<Components {...props}/>} {tab==='shared'&&<SharedProject {...props}/>} {tab==='jobs'&&<ProviderJobs {...props}/>}</>;
}
function Timeline({project,run,busy}){
  const [scenes,setScenes]=useState(project.storyboard?.scenes||[]),[selected,setSelected]=useState(''),[position,setPosition]=useState(0);const video=useRef(null);
  const signature=JSON.stringify(project.storyboard?.scenes);
  const timing=list=>list.map(({id,duration})=>({id,duration}));
  const {status:timelineStatus,reset:resetTimeline}=useAutosave(timing(scenes),value=>api(`/projects/${project.id}/timeline`,{method:'PUT',body:{scenes:value}}),{delay:1500,enabled:!busy&&!project.example&&scenes.length>0});
  useEffect(()=>{const next=project.storyboard?.scenes||[];setScenes(next);resetTimeline(timing(next));},[signature]);const total=scenes.reduce((sum,scene)=>sum+scene.duration,0);
  const move=(id,to)=>setScenes(previous=>{const copy=[...previous],from=copy.findIndex(scene=>scene.id===id);if(from<0||to<0||to>=copy.length)return previous;copy.splice(to,0,...copy.splice(from,1));return copy;});
  return <div className="timeline-editor"><div className="section-heading"><div><h3>El ritmo de tu historia</h3><p className="form-note">Arrastra escenas, ajusta su duración y revisa el punto exacto del vídeo.</p></div><span className="completion-badge">{total.toFixed(1)} s</span></div>{project.render&&<video ref={video} controls className="timeline-video" src={`/api/projects/${project.id}/files/${project.render.path}`}/>}
    <label>Posición de reproducción · {position.toFixed(1)} s<input aria-label="Posición del timeline" type="range" min="0" max={project.render?.duration||total||1} step="0.1" value={position} onChange={event=>{const value=Number(event.target.value);setPosition(value);if(video.current)video.current.currentTime=value;}}/></label>
    <div className="timeline-track">{scenes.map((scene,index)=><button key={scene.id} className={`timeline-block ${selected===scene.id?'selected':''}`} style={{flexGrow:scene.duration}} draggable={!busy} onDragStart={event=>event.dataTransfer.setData('text/plain',scene.id)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(!busy)move(event.dataTransfer.getData('text/plain'),index);}} onClick={()=>setSelected(scene.id)}><GripVertical size={14}/><span>{String(index+1).padStart(2,'0')} · {scene.title}</span><small>{scene.duration.toFixed(1)} s</small></button>)}</div>
    <div className="timeline-list">{scenes.map((scene,index)=><article key={scene.id}><div><strong>{index+1}. {scene.title}</strong><small>{scene.type} · {scene.narration}</small></div><label>Segundos<input aria-label={`Duración de ${scene.title}`} type="number" min="2" max="120" step="0.1" disabled={busy} value={scene.duration} onChange={event=>{const duration=Number(event.target.value);setScenes(previous=>previous.map(item=>item.id===scene.id?{...item,duration}:item));}}/></label><button className="icon-button" aria-label={`Subir ${scene.title}`} disabled={busy||index===0} onClick={()=>move(scene.id,index-1)}><ArrowUp size={16}/></button><button className="icon-button" aria-label={`Bajar ${scene.title}`} disabled={busy||index===scenes.length-1} onClick={()=>move(scene.id,index+1)}><ArrowDown size={16}/></button></article>)}</div><SaveStatus status={timelineStatus} idle="El orden y las duraciones se guardan automáticamente"/><p className="form-note">Continúa la producción para actualizar el MP4. Una voz que exceda el tiempo previsto ampliará su escena.</p>
  </div>;
}
function Components({project,run,busy}){const scenes=project.storyboard?.scenes||[],[sceneId,setSceneId]=useState(scenes[0]?.id||''),[words,setWords]=useState([]);const scene=scenes.find(scene=>scene.id===sceneId),combined=project.tasks.find(task=>task.kind==='scene'&&task.sceneId===sceneId)?.output;const component=part=>project.tasks.find(task=>task.kind===part&&task.sceneId===sceneId&&task.status==='completed')?.output;const captions=component('captions')||combined,voice=component('voice')||combined,visual=component('visual')||combined;const {status:captionStatus,reset:resetCaptions}=useAutosave({sceneId,words},value=>post(`/projects/${project.id}/resources/${value.sceneId}/captions/regenerate`,{words:value.words,start:false}),{delay:1500,enabled:!busy&&words.length>0});useEffect(()=>{const next=captions?.words||[];setWords(next);resetCaptions({sceneId,words:next});},[sceneId,JSON.stringify(captions?.words)]);const action=(part,verb,body)=>run(()=>post(`/projects/${project.id}/resources/${sceneId}/${part}/${verb}`,body));const file=value=>`/api/projects/${project.id}/files/${value}`;
  return <><h3>Revisa cada pieza por separado</h3><label>Escena<select aria-label="Escena" value={sceneId} onChange={event=>setSceneId(event.target.value)}>{scenes.map(scene=><option value={scene.id} key={scene.id}>{scene.title}</option>)}</select></label>{scene&&<><div className="component-grid">{[['voice','Narración',voice],['visual','Imagen o clip',visual],['captions','Subtítulos',captions]].map(([part,title,value])=>{const key=component(part)?.key||combined?.partKeys?.[part];return <article className="component-card" key={part}><h4>{title}</h4>{part==='voice'&&value?.audioPath?<audio controls src={file(value.audioPath)}/>:part==='visual'&&value?.visualPath?(value.visualKind==='video'?<video controls src={file(value.visualPath)}/>:<img src={file(value.visualPath)} alt={scene.title}/>):<p>{part==='visual'?scene.points.join(' → '):part==='captions'?`${value?.words?.length||0} palabras con tiempos`:scene.narration}</p>}<div className="component-actions"><button className="button secondary" disabled={busy||!key||Boolean(project.approvals?.[key])} onClick={()=>action(part,'approve')}><Check size={14}/>{project.approvals?.[key]?'Aprobado':'Aprobar'}</button><button className="button secondary" disabled={busy||project.example} onClick={()=>action(part,'regenerate')}><RefreshCw size={14}/>Regenerar</button></div></article>;})}</div><h4>Texto y tiempos de los subtítulos</h4><div className="caption-editor"><table><thead><tr><th>Texto</th><th>Inicio (s)</th><th>Fin (s)</th></tr></thead><tbody>{words.map((word,index)=><tr key={index}><td><input aria-label={`Palabra ${index+1}`} value={word.text} disabled={busy} onChange={event=>setWords(previous=>previous.map((item,i)=>i===index?{...item,text:event.target.value}:item))}/></td>{['start','end'].map(field=><td key={field}><input aria-label={`${field==='start'?'Inicio':'Fin'} de palabra ${index+1}`} type="number" step="0.01" min="0" disabled={busy} value={word[field]} onChange={event=>setWords(previous=>previous.map((item,i)=>i===index?{...item,[field]:Number(event.target.value)}:item))}/></td>)}</tr>)}</tbody></table></div><SaveStatus status={captionStatus} idle="Los subtítulos se guardan automáticamente"/></>}{project.audioReview&&<article className="knowledge-card"><h4>Lo que se reconoce en el audio real</h4>{project.audioReview.scenes.map(item=><section key={item.sceneId}><strong>{scenes.find(scene=>scene.id===item.sceneId)?.title}</strong><p>{item.text}</p><small>Diferencia con el guion: {Math.round(item.comparison.rate*100)}% · {item.engine}</small></section>)}</article>}</>;
}
function SharedProject({project,run,busy,notify}){const [entries,setEntries]=useState([]),[query,setQuery]=useState('');const refresh=()=>api('/library?q='+encodeURIComponent(query)).then(setEntries);useEffect(()=>{refresh();},[project.id,query]);const share=body=>run(async()=>{await post(`/projects/${project.id}/library`,body);await refresh();notify('Guardado en la biblioteca compartida.');});return <><h3>Reutiliza lo que ya has creado</h3><label>Buscar en la biblioteca<input value={query} onChange={event=>setQuery(event.target.value)}/></label><div className="shared-save"><h4>Guardar desde este proyecto</h4>{project.sources.map((source,index)=><button className="button secondary" disabled={busy} key={index} onClick={()=>share({kind:'source',id:source.id||`source-${index+1}`,name:source.name})}><BookOpen size={14}/>{source.name}</button>)}{project.assets?.map(asset=><button className="button secondary" disabled={busy} key={asset.id} onClick={()=>share({kind:'asset',id:asset.id,name:asset.name})}>{asset.name}</button>)}<button className="button secondary" disabled={busy} onClick={()=>share({kind:'style',name:'Estilo de '+project.title})}>Guardar estilo visual</button></div><div className="shared-grid">{entries.map(entry=><article className="knowledge-card" key={entry.id}><span className="completion-badge">{{source:'Fuente',asset:'Recurso',style:'Estilo'}[entry.kind]}</span><h4>{entry.name}</h4><p>{entry.source?.content.slice(0,150)||entry.tags.join(' · ')}</p><button className="button secondary" disabled={busy} onClick={()=>run(()=>post(`/projects/${project.id}/library/${entry.id}/import`))}><Download size={14}/>Usar en este proyecto</button></article>)}</div></>;
}
function ProviderJobs({project,run,busy}){const [jobs,setJobs]=useState([]),[urls,setUrls]=useState({});useEffect(()=>{api(`/projects/${project.id}/provider-jobs`).then(setJobs);},[project.updatedAt]);return <><h3>Solicitudes que sobreviven al cierre</h3><p className="form-note">Las solicitudes con identificador remoto se reanudan. Si el cierre impidió recibirlo, se pide reconciliar el resultado antes de repetir la generación.</p>{jobs.length===0&&<p className="form-note">Todavía no hay solicitudes externas.</p>}{jobs.map(job=><article className="knowledge-card" key={job.id}><span className="completion-badge">{job.status}</span><h4>{job.providerId}</h4><p>{job.request.prompt}</p>{job.remote?.request_id&&<small>Solicitud: {job.remote.request_id}</small>}{job.error&&<p>{job.error}</p>}{['uncertain','submitting'].includes(job.status)&&<><label>URL del recurso ya generado<input value={urls[job.id]||''} onChange={event=>setUrls(previous=>({...previous,[job.id]:event.target.value}))}/></label><button className="button secondary" disabled={busy||!urls[job.id]} onClick={()=>run(()=>post(`/projects/${project.id}/provider-jobs/${job.id}/reconcile`,{url:urls[job.id]}))}>Recuperar resultado</button><button className="button secondary" disabled={busy} onClick={()=>run(()=>post(`/projects/${project.id}/provider-jobs/${job.id}/reconcile`,{cancelled:true}))}>Descartar solicitud</button></>}</article>)}</>;
}
export function SharedLibrary({notify}){const [entries,setEntries]=useState([]);useEffect(()=>{api('/library').then(setEntries).catch(error=>notify(error.message,true));},[]);return <section className="settings-panel shared-workspace"><div className="section-heading"><div><h2>Conocimiento que conecta tus proyectos</h2><p className="form-note">Fuentes, medios y estilos reutilizables guardados en tu equipo.</p></div><span className="completion-badge">{entries.length} recursos compartidos</span></div><div className="shared-grid">{entries.map(entry=><article className="knowledge-card" key={entry.id}><h4>{entry.name}</h4><span className="completion-badge">{{source:'Fuente',asset:'Recurso',style:'Estilo'}[entry.kind]||entry.kind}</span><p>{entry.source?.content.slice(0,170)||entry.tags.join(' · ')}</p></article>)}</div></section>;}
export function LocalTools({notify}){const [status,setStatus]=useState(null),[busy,setBusy]=useState(false);const refresh=()=>api('/tools').then(setStatus);useEffect(()=>{refresh();const timer=setInterval(refresh,5000);return ()=>clearInterval(timer);},[]);const install=async kind=>{setBusy(true);try{await post(`/tools/${kind}/install`);await refresh();notify(kind==='whisper'?'Instalación local iniciada.':kind==='kokoro'?'Voz Kokoro preparada.':'Captura de audio preparada.');}catch(error){notify(error.message,true);}finally{setBusy(false);}};return <section className="settings-panel"><h2>Herramientas locales</h2><div className="local-tool-grid">{[['whisper','Revisión del audio','Transcripción local del MP4, contraste con guion y subtítulos.'],['ocr','PDF escaneados','Reconocimiento en español e inglés. Descarga los modelos al primer uso.'],['audio','Sonido del PC','Captura WASAPI de la salida de sonido, sin instalar controladores.'],['kokoro','Voz Kokoro','Voz neuronal local en español (Kokoro-82M). Instala un Python aislado en .tools.']].map(([key,name,description])=><article key={key}><span className={status?.[key]?.ready?'green-dot':'gray-dot'}/><h3>{name}</h3><p>{description}</p>{key!=='ocr'&&<button className="button secondary" disabled={busy||status?.[key]?.ready||key==='whisper'&&status?.installation?.status==='running'} onClick={()=>install(key)}>{status?.[key]?.ready?'Preparado':key==='whisper'&&status?.installation?.status==='running'?'Instalando…':'Preparar herramienta'}</button>}</article>)}</div></section>;}
