import React,{useState,useEffect} from 'react';
import {Image,Film,Globe,Search,Upload,Eye,Check,ExternalLink,Layers,X,Music,ShieldCheck} from 'lucide-react';
import {studioApi,encodeFile,uploadFile} from './studio-api.mjs';
import './resources.css';
import {ResourceClipEditor} from './DesignStudio.jsx';

const types=[['all','Todo',Layers],['image','Imágenes',Image],['video','Vídeos',Film],['page','Páginas',Globe],['music','Audio',Music]];
const recommendations={use:'Recomendado',reserve:'En reserva',reject:'Descartado'};
export const approvalKinds=['research','resource-review','script','storyboard','production-plan','screencast','scene','voice','visual','captions'];
export function ExecutionMode({options={},onChange,disabled=false}){return <label className="execution-mode">Modo de ejecución<select aria-label="Modo de ejecución" disabled={disabled} value={options.approvalGates?'supervised':'automatic'} onChange={e=>onChange(e.target.value==='supervised')}><option value="automatic">Automático · hasta el vídeo final</option><option value="supervised">Paso a paso · con supervisión</option></select><small>{options.approvalGates?'Revisa cada etapa y apruébala para continuar.':'El equipo investiga, valora recursos, diseña y produce.'}</small></label>;}

export function ResourceLibrary({project,act}){
  const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[kind,setKind]=useState('image'),[provider,setProvider]=useState('commons'),[providers,setProviders]=useState([]),[url,setUrl]=useState(''),[urlKind,setUrlKind]=useState('page'),[busy,setBusy]=useState(false),[sceneIds,setSceneIds]=useState({});
  const active=busy||['running','planning','rendering'].includes(project.status),base='/projects/'+project.id,file=value=>'/api'+base+'/files/'+value;
  useEffect(()=>{studioApi('/settings').then(data=>setProviders(data.providers.filter(item=>item.ready&&item.adapter==='pexels'))).catch(()=>{});},[]);
  useEffect(()=>{act(()=>studioApi(base+'/resources'));},[project.id]);
  const resources=[...(project.resources||[]),...(project.assets||[]).filter(asset=>!(project.resources||[]).some(resource=>resource.assetId===asset.id)).map(asset=>({...asset,assetId:asset.id,status:'ready'}))];
  const visible=resources.filter(resource=>filter==='all'||resource.kind===filter);
  const perform=async fn=>{setBusy(true);try{await act(fn);}finally{setBusy(false);}};
  const post=(suffix,body)=>perform(()=>studioApi(base+suffix,{method:'POST',body}));
  const upload=async e=>{const files=[...e.target.files];e.target.value='';await perform(async()=>{for(const item of files)await uploadFile(project.id,item);});};
  const assign=resource=>{const scene=project.storyboard.scenes.find(item=>item.id===sceneIds[resource.id]);return perform(()=>studioApi(base+'/scenes/'+scene.id,{method:'PATCH',body:{type:resource.kind==='video'?'video':'image',visual:{...scene.visual,assetId:resource.assetId}}}));};
  return <section className="resource-library">
    <div className="resource-hero"><span className="resource-hero-icon"><Layers size={26}/></span><div><h3>Recursos para tu historia</h3><p>Páginas, imágenes y vídeos reunidos durante la investigación. Valora lo que ayuda a explicar y elige dónde usarlo.</p></div></div>
    <div className="resource-actions"><label className="button secondary"><Upload size={15}/>Importar medios<input hidden type="file" multiple accept="image/*,video/mp4,video/webm,video/quicktime,.mov,.mkv,.m4v,audio/*,.m4a,.flac" disabled={active} onChange={upload}/></label><button className="button primary" disabled={active||!resources.some(resource=>['image','video'].includes(resource.kind)&&resource.decision!=='reject')} onClick={()=>post('/resources/review',{})}><Eye size={15}/>Valorar imágenes y vídeos</button></div>
    <details className="resource-discovery"><summary><Search size={15}/>Buscar o añadir recursos web</summary><p className="form-note">Commons no necesita clave. Pexels usa la conexión configurada. Los candidatos se inspeccionan antes del storyboard.</p><div className="form-row"><label>Buscar medios<input placeholder="Router, asignación de IP…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Tipo de medio<select value={kind} onChange={e=>setKind(e.target.value)}><option value="image">Imagen</option><option value="video">Vídeo</option></select></label><label>Biblioteca<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="commons">Wikimedia Commons</option>{project.options?.externalMedia&&providers.map(item=><option value={item.id} key={item.id}>Pexels · {item.id}</option>)}</select></label></div><button className="button secondary" disabled={active||!project.options?.webResearch||!query.trim()} onClick={()=>post('/resources/search',{query,kind,provider})}><Search size={14}/>Buscar candidatos</button><div className="form-row resource-url"><label>Página o archivo multimedia<input placeholder="https://…" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Tipo de recurso<select value={urlKind} onChange={e=>setUrlKind(e.target.value)}><option value="page">Página</option><option value="image">Imagen</option><option value="video">Vídeo</option></select></label></div><button className="button secondary" disabled={active||!project.options?.webResearch||!url} onClick={()=>post(urlKind==='page'?'/web-source':'/resources/add',{url,kind:urlKind,name:'Recurso web',sourceUrl:url})}>Añadir a Recursos</button>{!project.options?.webResearch&&<p className="form-note">Activa «Permitir investigación web» en el perfil para consultar páginas y descubrir medios.</p>}</details>
    <div className="resource-filters" role="group" aria-label="Filtrar recursos">{types.map(([value,label,Icon])=><button key={value} aria-pressed={filter===value} className={filter===value?'selected':''} onClick={()=>setFilter(value)}><Icon size={14}/>{label}<span>{resources.filter(resource=>value==='all'||resource.kind===value).length}</span></button>)}</div>
    {!visible.length?<div className="resource-empty"><Image size={32}/><h4>{resources.length?'No hay recursos de este tipo':'Aquí empieza tu biblioteca'}</h4><p>Importa archivos o deja que el investigador reúna páginas y candidatos para el vídeo.</p></div>:<div className="resource-grid">{visible.map(resource=>{
      const asset=project.assets?.find(item=>item.id===resource.assetId),assessment=resource.assessment,used=project.storyboard?.scenes.filter(scene=>resource.assetId&&(scene.visual?.assetId===resource.assetId||scene.composition?.layers?.some(layer=>layer.type==='media'&&layer.media?.assetId===resource.assetId)))||[],discarded=resource.decision==='reject'||assessment?.recommendation==='reject'&&resource.decision!=='use';
      return <article className={'resource-card '+(discarded?'resource-discarded':'')} key={resource.id}>
        <div className={'resource-preview resource-preview-'+resource.kind}>{resource.kind==='page'?<><Globe size={32}/><span>{resource.status==='consulted'?'Página consultada':'Referencia sin consultar'}</span></>:resource.kind==='image'&&(resource.previewPaths?.[0]?.path||asset?.path)?<img loading="lazy" src={file(resource.previewPaths?.[0]?.path||asset.path)} alt={resource.name}/>:resource.kind==='video'&&asset?.path?<video controls preload="metadata" poster={resource.previewPaths?.[0]?.path?file(resource.previewPaths[0].path):undefined} src={file(asset.path)}/>:resource.kind==='music'&&asset?.path?<audio controls src={file(asset.path)}/>:<><Film size={30}/><span>Candidato por preparar</span></>}{assessment?.inspected&&<span className="resource-score"><ShieldCheck size={13}/>{assessment.score}/100</span>}</div>
        <div className="resource-card-body"><div className="resource-card-meta"><span>{types.find(([type])=>type===resource.kind)?.[1]}</span><span className={'resource-recommendation '+(resource.decision||assessment?.recommendation||'')}>{resource.decision==='use'?'Seleccionado':recommendations[resource.decision||assessment?.recommendation]||'Sin valorar'}</span></div><h4>{resource.name}</h4>
          {resource.metadata&&<small>{resource.metadata.width} × {resource.metadata.height}{resource.metadata.duration?' · '+resource.metadata.duration.toFixed(1)+' s':''}</small>}
          {resource.kind==='page'&&<p className="resource-excerpt">{resource.content?.replace(/^URL:[^]*?\nRecuperada:[^\n]*\n/,'').slice(0,260)||'El enlace está guardado; su contenido no se ha recuperado.'}</p>}
          {resource.kind!=='page'&&<div className="resource-provenance"><small>{resource.author||'Autor no indicado'} · {resource.license||'Licencia no indicada'}</small>{resource.licenseUrl&&/^https?:\/\//.test(resource.licenseUrl)&&<a href={resource.licenseUrl} target="_blank" rel="noreferrer">Ver licencia</a>}</div>}
          {(resource.sourceUrl||resource.url)&&<a className="resource-source" href={resource.sourceUrl||resource.url} target="_blank" rel="noreferrer"><ExternalLink size={13}/>Abrir procedencia</a>}
          {resource.error&&<p className="inline-error">{resource.error}</p>}
          {assessment&&<details className="resource-assessment"><summary>{assessment.inspected?'Ver valoración visual':'Inspección pendiente'}</summary><p><strong>Pertinencia:</strong> {assessment.relevance}</p><p><strong>Calidad:</strong> {assessment.quality}</p><p><strong>Composición:</strong> {assessment.compositionFit}</p>{assessment.suggestedUse&&<p><strong>Uso propuesto:</strong> {assessment.suggestedUse}</p>}{assessment.limitations?.map((limit,index)=><p key={index}>{limit}</p>)}<small>{assessment.model} · {new Date(assessment.at).toLocaleString('es')}</small></details>}
          {used.length>0&&<div className="resource-used"><Check size={13}/>En {used.map(scene=>scene.title).join(', ')}</div>}
          {['image','video'].includes(resource.kind)&&<><div className="resource-card-actions">{!resource.previewPaths?.length&&<button className="button secondary" disabled={active} onClick={()=>post('/resources/preview',{resourceId:resource.id})}><Eye size={13}/>Preparar</button>}<button className="text-button" disabled={active} onClick={()=>perform(()=>studioApi(base+'/resources/'+resource.id,{method:'PATCH',body:{decision:resource.decision==='use'?null:'use'}}))}><Check size={13}/>{resource.decision==='use'?'Quitar selección':'Seleccionar'}</button><button className="text-button" disabled={active} onClick={()=>perform(()=>studioApi(base+'/resources/'+resource.id,{method:'PATCH',body:{decision:resource.decision==='reject'?null:'reject'}}))}><X size={13}/>{resource.decision==='reject'?'Recuperar':'Descartar'}</button><button className="text-button" disabled={active} onClick={()=>perform(()=>studioApi(base+'/resources/'+resource.id,{method:'PATCH',body:{decision:resource.decision==='reserve'?null:'reserve'}}))}>{resource.decision==='reserve'?'Quitar reserva':'Dejar en reserva'}</button></div>{asset&&project.storyboard&&!project.example&&<div className="resource-assign"><select aria-label={'Escena para '+resource.name} value={sceneIds[resource.id]||''} disabled={active||discarded} onChange={e=>setSceneIds({...sceneIds,[resource.id]:e.target.value})}><option value="">Asignar a una escena…</option>{project.storyboard.scenes.map(scene=><option key={scene.id} value={scene.id}>{scene.title}</option>)}</select><button className="button secondary" disabled={active||discarded||!sceneIds[resource.id]} onClick={()=>assign(resource)}>Usar</button></div>}{resource.kind==='video'&&asset&&<ResourceClipEditor project={project} resource={resource} asset={asset} act={act} disabled={active||discarded}/>}</>}
        </div>
      </article>;
    })}</div>}
  </section>;
}

export function SupervisionPanel({project,act,onReview}){
  const [busy,setBusy]=useState(false),pending=project.tasks.filter(task=>task.status==='completed'&&approvalKinds.includes(task.kind)&&!task.approved);
  if(!project.options?.approvalGates||project.status!=='needs-approval')return null;
  const approve=async()=>{setBusy(true);try{await act(()=>studioApi('/projects/'+project.id+'/stage/approve',{method:'POST',body:{}}));}finally{setBusy(false);}};
  return <div className="supervision-banner"><span className="stat-icon mint"><Eye size={20}/></span><div><strong>Esta etapa espera tu revisión</strong><p>{pending.map(task=>task.label).join(' · ')}</p><small>Revisa los resultados, edita o regenera antes de aprobar.</small></div><button className="button secondary" onClick={onReview}>Revisar etapa</button><button className="button primary" disabled={busy||!pending.length} onClick={approve}>Aprobar etapa y continuar</button></div>;
}

export function StageApprovals({project,act}){
  const [busy,setBusy]=useState(false),base='/projects/'+project.id,file=value=>'/api'+base+'/files/'+value;
  const approve=async task=>{setBusy(true);try{await act(()=>studioApi(base+'/artifacts/'+task.id+'/approve',{method:'POST'}));}finally{setBusy(false);}};
  return <div className="resource-library"><h3>Revisar cada etapa</h3><p className="form-note">Lee el resultado y revisa los medios en Recursos. Puedes editar el storyboard o regenerar una tarea antes de aprobar.</p>{project.plan&&<details className="stage-card"><summary>Plan del director y dependencias</summary><p>{project.plan.reasoning}</p>{project.tasks.map(task=><p key={task.id}><strong>{task.label}</strong> · {task.status} · espera {task.dependencies.join(', ')||'sin dependencias'}</p>)}</details>}{project.tasks.filter(task=>task.output&&approvalKinds.includes(task.kind)).map(task=><article className="stage-card" key={task.id}><div className="version-row"><strong>{task.label}</strong><div className="resource-card-actions"><button className="button secondary" disabled={busy||['running','planning','rendering'].includes(project.status)} onClick={async()=>{setBusy(true);try{await act(()=>studioApi(base+'/regenerate',{method:'POST',body:{taskId:task.id}}));}finally{setBusy(false);}}}><Eye size={13}/>Regenerar</button><button className="button secondary" disabled={busy||task.approved} onClick={()=>approve(task)}>{task.approved?'Aprobado':'Aprobar artefacto'}</button></div></div><p>{task.output.summary||task.output.reasoning||task.output.title}</p>{task.output.scenes?.map(scene=><section className="artifact-scene" key={scene.id}><strong>{scene.title}</strong><p>{scene.narration}</p>{scene.points?.length>0&&<ul>{scene.points.map((point,index)=><li key={index}>{point}</li>)}</ul>}</section>)}{task.output.sources?.map((source,index)=><p key={index}>{/^https?:\/\//.test(source.url)?<a href={source.url} target="_blank" rel="noreferrer">{source.title}</a>:source.title}</p>)}{task.output.resources?.map(resource=><div key={resource.resourceId}><p><strong>{project.resources?.find(item=>item.id===resource.resourceId)?.name||resource.resourceId}</strong> · {resource.inspected?resource.score+'/100':'Sin inspección'} · {recommendations[resource.recommendation]}</p><p>{resource.relevance}</p><p>{resource.compositionFit} {resource.suggestedUse}</p></div>)}{task.output.audioPath&&<audio controls src={file(task.output.audioPath)}/>} {task.output.visualPath&&(task.output.visualKind==='video'?<video controls src={file(task.output.visualPath)}/>:<img className="review-frame" src={file(task.output.visualPath)} alt="Recurso visual"/>)}{task.output.recordingId&&project.recordings?.find(item=>item.id===task.output.recordingId)?.path&&<video controls src={file(project.recordings.find(item=>item.id===task.output.recordingId).path)}/>}<details><summary>Ver artefacto completo</summary><pre>{JSON.stringify(task.output,null,2)}</pre></details></article>)}</div>;
}
